### PR TITLE
Pull evm_address for contract logs

### LINKED ISSUE #644: The log object should return the evm address not the hedera entity address
### Description

According to the [eth json rpc spec](https://github.com/etclabscore/ethereum-json-rpc-specification/blob/97178e7dc3b417318e2977171254f6e21d080076/openrpc.json#L1250) the log object address(i.e. `Log.address`) should be the evm address of the contract that emitted the event. However, the relay currently returns the Hedera entity id for the contract in evm address format(e.g. `0x0000000000000000000000000000000000000409` i.e. _0.0.1033_) when it should instead return the actual evm address of the contract i.e. either the `create1` or `create2` address.

A known impact is on the [subgraph data source templates](https://thegraph.com/docs/en/developing/creating-a-subgraph/#instantiating-a-data-source-template) that enables the subgraph to index logs on created contracts. For example, a `Factory` contract creates a `Child` contract and the `Factory` emits an event(say `ChildCreated`) containing the `create2` address of the `Child` contract. The subgraph handler for this `ChildCreated` event has access to the `create2` address from the `event.params` and creates a template index for that `Child` contract. However since the Hedera relay returns the Hedera entity id for the `Child` contract instead of the evm address on `Log.address` the `Child` contract's logs aren't indexed(at least for `create2` contract's at this point since `create1` addresses are currently identical to the contract's entity id).

### Steps to reproduce

1. Pull and checkout to [this branch]()
2. Start up the hedera local node
3. Start up the local graph node
4. Run `npm run test:hgf` to deploy and test the `GreeterFactory` and created `Greeter` contracts
5. In the `subgraph-example` update the `GreeterFactory` `address` and `startBlock` accordingly
6. create and deploy the subgraph to the local graph node
7. Observe that the child Greeter contract using `create1` has been [templated correctly](https://github.com/hashgraph/hedera-json-rpc-relay/pull/642/files#r999654754) as it's `handleGreetingSet` event handler has been called accordingly and observe that the child `Greeter` contract using `create2` has [not been templated correctly](https://github.com/hashgraph/hedera-json-rpc-relay/pull/642/files#r999656054) as it's handleGreetingSet is not triggered due to the address mismatch.

### Additional context

_No response_

### Hedera network

other

### Version

@hashgraph/hedera-local@2.0.1

### Operating system

macOS

### PR DESCRIPTION
**Pull request by Nana-EC**
Signed-off-by: Nana Essilfie-Conduah <nana@swirldslabs.com>

**Description**:
Provide a workaround to pull evm_address for contract logs
- for logs retrieve evm_address from mirror node

**Related issue(s)**:

Fixes #644 

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

### CODE REVIEW

**Comment by dimitrovmaksim** [comment]
I just realised that this may not fix the Graph issue. The problem is that when using dynamic dataSource templates for child contracts, and the child contract is created with create2, the dynamic datasource will be created with the child contract's `evm_address`, then when the graph node does a `eth_getLogs()` method call for a datasource it would pass `address`, `topic0`, `fromBlock` and `toBlock` filters. So if the mirror node does not filter the logs by the `evm_address` we still wont have matches for that evm_address.

File: packages/relay/src/lib/eth.ts [hunk 1]
```diff
@@ -1320,24 +1320,31 @@ export class EthImpl implements Eth {
...
-        removed: false,
-        topics: log.topics,
-        transactionHash: EthImpl.toHash32(log.transaction_hash),
-        transactionIndex: EthImpl.numberTo0x(log.transaction_index)
-      });
-    });
+    return Promise.all(
+      result.logs.map(async log => {
+        return new Log({
+          address: await this.getContractEvmAddress(log.address, requestId),
```
Comment (steven-sheehy) [inline packages/relay/src/lib/eth.ts:1326]: The log address can repeat multiple times within the payload. `/api/v1/contracts/{id}` is a heavyweight call that returns large byte arrays. We should minimize calls to this API by collecting `log.address` into a set then calling the distinct addresses outside this loop. It's a performance optimization that makes the code not as clean but is necessary to reduce the load on mirror node.

File: packages/relay/src/lib/eth.ts [hunk 2]
```diff
@@ -1320,24 +1320,31 @@ export class EthImpl implements Eth {
...
   }
 
   async maxPriorityFeePerGas(requestId?: string): Promise<string> {
     const requestIdPrefix = formatRequestIdMessage(requestId);
     this.logger.trace(`${requestIdPrefix} maxPriorityFeePerGas()`);
     return EthImpl.zeroHex;
   }
+
+  private async getContractEvmAddress(address: string, requestId: string | undefined) {
+    const result = await this.mirrorNodeClient.getContract(address, requestId);
```
Comment (steven-sheehy) [inline packages/relay/src/lib/eth.ts:1347]: Can we cache this lookup with some fixed size LRU cache?

**Review by steven-sheehy — CHANGES_REQUESTED** [review]

File: packages/relay/src/lib/eth.ts (hunk 2 above)
Comment (Nana-EC) [reply packages/relay/src/lib/eth.ts:1347]: Can use something like
- check for `contractEvmAddress` i.e 
```
 let contractEvmAddress = cache.get(cachedLabel);
```
- if absent make mirror node call and when done.
```
cache.set(cachedLabel, <contractEvmAddress>, constants.CACHE_TTL.ONE_HOUR);
```

File: packages/relay/src/lib/eth.ts (hunk 1 above)
Comment (Nana-EC) [reply packages/relay/src/lib/eth.ts:1326]: Agreed.
Prefer the caching option since this is just a workaround till Mirror Node adopts similar logic.
Then this work would go away.

File: packages/relay/src/lib/eth.ts (hunk 2 above)
Comment (dimitrovmaksim) [reply packages/relay/src/lib/eth.ts]: I've added the caching, added a test. 

One question, do we need the `result.evm_address || address`, it seems `evm_address` can't be `null` unless `result` is null, in which case `result.evm_address` will throw a `TypeError: Cannot read properties of null (reading 'evm_address')`. Also in this case `result` would be `null` if the mirror node returns 400 or 404, wouldn't we want  to throw an error in the case when the request result is `null`?

Comment (steven-sheehy) [reply packages/relay/src/lib/eth.ts]: I think it might be better to catch any errors during `getContractEvmAddress()` and return the `log.address` as a fallback.

File: packages/relay/src/lib/eth.ts [hunk 3]
```diff
@@ -1316,24 +1316,44 @@ export class EthImpl implements Eth {
...
+  private async getLogEvmAddress(address: string, requestId: string | undefined) {
+    const cachedLabel = `getLogEvmAddress.${address}`;
+    let contractAddress = cache.get(cachedLabel);
+
+    // If contractAddress === undefined it means there's no cache record
+    // and a mirror node request should be executed.
+    if(contractAddress === undefined) {
+      const contract = await this.mirrorNodeClient.getContract(address, requestId);
+      contractAddress = contract.evm_address;
+      cache.set(cachedLabel, contractAddress, constants.CACHE_TTL.ONE_HOUR);
```
Comment (steven-sheehy) [inline packages/relay/src/lib/eth.ts:1354]: It seems `js-cache` doesn't support a fixed size? I hope you don't get a lot of requests in that one hour and cause a memory overflow. This is a security issue. You guys should investigate an alternative library in a follow up.

File: packages/relay/src/lib/eth.ts [hunk 4]
```diff
@@ -1316,24 +1316,44 @@ export class EthImpl implements Eth {
...
     return EthImpl.zeroHex;
   }
+
+  private async getLogEvmAddress(address: string, requestId: string | undefined) {
+    const cachedLabel = `getLogEvmAddress.${address}`;
+    let contractAddress = cache.get(cachedLabel);
+
+    // If contractAddress === undefined it means there's no cache record
+    // and a mirror node request should be executed.
+    if(contractAddress === undefined) {
```
Comment (steven-sheehy) [inline packages/relay/src/lib/eth.ts:1351]: nit: Spacing here and elsewhere doesn't match the relay standard.

**Review by steven-sheehy — DISMISSED** [review]

**Review by steven-sheehy — APPROVED** [review]

**Review by Nana-EC — COMMENTED** [review]
LG.
Can't approve since i started the PR so consider this my signoff

File: packages/relay/src/lib/eth.ts (hunk 3 above)
Comment (Nana-EC) [reply packages/relay/src/lib/eth.ts:1354]: Added https://github.com/hashgraph/hedera-json-rpc-relay/issues/658 for next sprint

**Review by georgi-l95 — APPROVED** [review]
LGTM
