### PR TITLE
eth_feeHistory invalid cached response

### LINKED ISSUE #881: `eth_feeHistory` invalid cached response
### Description

The cache for eth_feeHistory is set no matter what the input is. That's resolved to an invalid response :point_down: 
- make a request with "latest" param
- the relay caches the response
- same response will be returned for the next 1 hour (cache TTL) no matter that there is a new block in that interval

#### Proposed fix:
- do not cache "latest" or "pending" queries
- refactor the cache key to include `blockCount`, `newestBlock` and `rewardPercentiles`с

### Steps to reproduce

Execute multiple `eth_feeHistory` calls and observe that `oldestBlock` is always the same.
```
{
  "method": "eth_feeHistory",
  "params": ["0x4", "latest", [50]],
  "id": 2,
  "jsonrpc": "2.0"
}
```

### Additional context

_No response_

### Hedera network

other

### Version

latest

### Operating system

None

### PR DESCRIPTION
**Pull request by natanasow**
Signed-off-by: nikolay <n.atanasow94@gmail.com>

**Description**:

**Related issue(s)**:

Fixes #881

**Notes for reviewer**:

**Checklist**

- [x] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

### CODE REVIEW

File: packages/relay/src/lib/eth.ts [hunk 1]
```diff
@@ -188,13 +188,14 @@ export class EthImpl implements Eth {
         return EthImpl.feeHistoryZeroBlockCountResponse;
       }
 
-      let feeHistory: object | undefined = this.cache.get(constants.CACHE_KEY.FEE_HISTORY);
+      const cacheKey = `${constants.CACHE_KEY.FEE_HISTORY}_${blockCount}_${newestBlock}_${rewardPercentiles?.join('')}`;
```
Comment (Nana-EC) [inline packages/relay/src/lib/eth.ts:191]: Do we need all the params?

**Review by Nana-EC — APPROVED** [review]

File: packages/relay/src/lib/eth.ts (hunk 1 above)
Comment (natanasow) [reply packages/relay/src/lib/eth.ts:191]: Yep, in any other case the returned response will not be valid or fulfilled :confused:

**Review by Nana-EC — APPROVED** [review]
