### PR TITLE
fix: added newFilter to paramRearrangementMap for WS server

### LINKED ISSUE #3114: [WS Regression] eth_newFilter is failing
### Description

The test cases below are failing.
```bash
RPC Server Acceptance Tests
       Acceptance tests
         @web-socket-batch-2 eth_newFilter
           Standard Web Socket
             @release Should execute eth_newFilter on Standard Web Socket and handle valid requests correctly:
     AssertionError: expected undefined to exist
      at Suite.<anonymous> (packages/ws-server/tests/acceptance/newFilter.spec.ts:90:26)
      at Generator.next (<anonymous>)
      at fulfilled (packages/ws-server/tests/acceptance/newFilter.spec.ts:24:58)
```

```bash
RPC Server Acceptance Tests
       Acceptance tests
         @web-socket-batch-2 eth_newFilter
           Ethers Web Socket Provider
             @release Should execute eth_newFilter on Ethers Web Socket Provider and handle valid requests correctly:
     Error: could not coalesce error (error={ "code": -32000, "message": "Exceeded maximum block range: 1000" }, payload={ "id": 1, "jsonrpc": "2.0", "method": "eth_newFilter", "params": [ { "address": [ "0xadF86D6D774AA2507380E0264e5f8052035B5BE8" ], "fromBlock": "0x0", "toBlock": "latest" } ] }, code=UNKNOWN_ERROR, version=6.13.2)
      at makeError (packages/ws-server/node_modules/ethers/src.ts/utils/errors.ts:694:21)
      at WebSocketProvider.getRpcError (packages/ws-server/node_modules/ethers/src.ts/providers/provider-jsonrpc.ts:1059:25)
      at /Users/user/development/hashgraph/hedera-json-rpc-relay/packages/ws-server/node_modules/ethers/src.ts/providers/provider-jsonrpc.ts:563:45
      at processTicksAndRejections (node:internal/process/task_queues:95:5)
```

### Steps to reproduce

1. Run `npm run release_ws`
2. Observe the failing test

### Additional context

_No response_

### Hedera network

testnet, previewnet

### Version

0.58.0-rc1

### Operating system

None

### PR DESCRIPTION
**Pull request by quiet-node**
**Description**:
There's a regression in the WS server that breaks the `eth_newFilter` WS endpoint. Essentially, before the data is submitted to the Relay, there’s a step to rearrange the parameters for certain special endpoints that have a different parameter order than others. This step is handled by the `paramRearrangementMap`, but it missed the `newFilter` endpoint, so the parameters weren't ordered correctly, causing the `eth_newFilter` endpoint to fail.

This PR simply adds the `newFilter` method to the `paramRearrangementMap`, fixing the issue.

**Related issue(s)**:

Fixes #3114 

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

### CODE REVIEW

File: packages/ws-server/src/controllers/index.ts [hunk 1]
```diff
@@ -81,6 +81,7 @@ const handleSendingRequestsToRelay = async ({
       chainId: (_, requestDetails) => [requestDetails],
       estimateGas: (params, requestDetails) => [...params, null, requestDetails],
       getStorageAt: (params, requestDetails) => [params[0], params[1], requestDetails, params[2]],
+      newFilter: (params, requestDetails) => [params[0], params[1], requestDetails, params[2], params[3]],
```
Comment (Nana-EC) [inline packages/ws-server/src/controllers/index.ts:84]: Nice catch, there should be a test to confirm this and ensure no regressions in the future

**Review by Nana-EC — CHANGES_REQUESTED** [review]
Looks good but needs tests

File: packages/ws-server/src/controllers/index.ts (hunk 1 above)
Comment (quiet-node) [reply packages/ws-server/src/controllers/index.ts]: Good point. Added some unit tests

**Review by Nana-EC — APPROVED** [review]

**Review by ebadiere — APPROVED** [review]
LG.
