### PR TITLE
returning synthetic transaction when fetching it using eth_getTransac…

### LINKED ISSUE #1794: eth_getTransactionByHash is not getting Synthetic Transactions
### Description

When trying to get the details of a synthetic transaction using method `eth_getTransactionByHash`  nothing shows up.
But using the same hash on a different method `eth_getTransactionReceipt` it yields the synthetic transaction details.

My guess is that the method `eth_getTransactionByHash` is not populating synthetic transactions.

### Steps to reproduce

**First is needed to fetch the Block that contains the synthetic transaction:**
```
curl --location 'http://127.0.0.1:7546' \
--header 'Content-Type: application/json' \
--data '{
    "jsonrpc": "2.0",
    "method": "eth_getBlockByNumber",
    "params": ["0x2c8603", true],
    "id": 1
}'
```

**eth_getTransactionReceipt Request:**
```curl

curl --location 'https://testnet.hashio.io/api' \
--header 'Content-Type: application/json' \
--data '{
    "method": "eth_getTransactionReceipt",
    "params": [

       "0xeb34a144a45506b518334144c3c2618db2e2515dcfa22065e00eb1e73a42d631"
    ],
    "id": 68,
    "jsonrpc": "2.0"
}'

```

**Response:**
```
{
    "result": {
        "blockHash": "0x882d5097a6d8a81af0e6a15948c6163496871e2489c64985818646f334ca4731",
        "blockNumber": "0x2c8603",
        "contractAddress": "0x0000000000000000000000000000000000445e75",
        "cumulativeGasUsed": "0x0",
        "effectiveGasPrice": "0x199c82cc000",
        "from": "0x0000000000000000000000000000000000000000",
        "gasUsed": "0x0",
        "logs": [
            {
                "address": "0x0000000000000000000000000000000000445e75",
                "blockHash": "0x882d5097a6d8a81af0e6a15948c6163496871e2489c64985818646f334ca4731",
                "blockNumber": "0x2c8603",
                "data": "0x0000000000000000000000000000000000000000000000000000000000000000",
                "logIndex": "0x0",
                "removed": false,
                "topics": [
                    "0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef",
                    "0x000000000000000000000000000000000000000000000000000000000006c330",
                    "0x0000000000000000000000000000000000000000000000000000000000445e76",
                    "0x0000000000000000000000000000000000000000000000000000000000000001"
                ],
                "transactionHash": "0xeb34a144a45506b518334144c3c2618db2e2515dcfa22065e00eb1e73a42d631",
                "transactionIndex": "0x3"
            }
        ],
        "logsBloom": "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
        "root": "0x0000000000000000000000000000000000000000000000000000000000000000",
        "status": "0x1",
        "to": "0x0000000000000000000000000000000000445e75",
        "transactionHash": "0xeb34a144a45506b518334144c3c2618db2e2515dcfa22065e00eb1e73a42d631",
        "transactionIndex": "0x3",
        "type": null
    },
    "jsonrpc": "2.0",
    "id": 68
}
```

-----

**eth_getTransactionByHash Request**

```
curl --location 'https://testnet.hashio.io/api' \
--header 'Content-Type: application/json' \
--data '{
    "method": "eth_getTransactionByHash",
    "params": [
        "0xeb34a144a45506b518334144c3c2618db2e2515dcfa22065e00eb1e73a42d631"
    ],
    "id": 1,
    "jsonrpc": "2.0"
}'
```

**Response:**

```
{
    "result": null,
    "jsonrpc": "2.0",
    "id": 1
}
```

### Additional context

_No response_

### Hedera network

testnet

### Version

v0.32.0

### Operating system

None

### PR DESCRIPTION
**Pull request by AlfredoG87**
**Description**:
It was reported by a member of the community that after fetching a block that contained synthetic transactions, it was posisble to fetch the transaction details using `eth_getTransactionReceipt` but not `eth_getTransactionByHash`.
So we are also including `synthetic transactions` on `eth_getTransactionByHash` to keep consistency between methods.

**Related issue(s)**:

Fixes #1794 

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

### CODE REVIEW

File: packages/relay/src/lib/eth.ts [hunk 1]
```diff
@@ -1696,6 +1696,20 @@ export class EthImpl implements Eth {
    */
   async getTransactionByHash(hash: string, requestIdPrefix?: string) {
     this.logger.trace(`${requestIdPrefix} getTransactionByHash(hash=${hash})`, hash);
+
+    // check if tx is synthetic and exists in cache
+    const cacheKeySyntheticLog = `${constants.CACHE_KEY.SYNTHETIC_LOG_TRANSACTION_HASH}${hash}`;
+    const cachedLog = await this.cacheService.getSharedWithFallback(
```
Comment (Nana-EC) [inline packages/relay/src/lib/eth.ts:1702]: Q: should we guard this on `this.shouldPopulateSyntheticContractResults` rather so that the cache query is only made when applicable?

File: packages/relay/src/lib/eth.ts [hunk 2]
```diff
@@ -1735,7 +1749,7 @@ export class EthImpl implements Eth {
     this.logger.trace(`${requestIdPrefix} getTransactionReceipt(${hash})`);
 
     const cacheKey = `${constants.CACHE_KEY.ETH_GET_TRANSACTION_RECEIPT}_${hash}`;
-    const cachedResponse = this.cacheService.get(cacheKey, EthImpl.ethGetTransactionReceipt, requestIdPrefix);
+    const cachedResponse = false; //this.cacheService.get(cacheKey, EthImpl.ethGetTransactionReceipt, requestIdPrefix);
```
Comment (Nana-EC) [inline packages/relay/src/lib/eth.ts:1752]: Left over changes to be resolved

**Review by Nana-EC — CHANGES_REQUESTED** [review]
Looking good.
1 question and a left over item to review.

Also please update PR description with insight into what the problem was and how this fixes it

File: packages/relay/src/lib/eth.ts (hunk 2 above)
Comment (AlfredoG87) [reply packages/relay/src/lib/eth.ts:1752]: I forgot to return this to how it was 😓 
it was there for testing purposes.
Thank you for noticing this.

File: packages/relay/src/lib/eth.ts (hunk 1 above)
Comment (AlfredoG87) [reply packages/relay/src/lib/eth.ts:1702]: agreed

Comment (AlfredoG87) [reply packages/relay/src/lib/eth.ts]: ✅  done

File: packages/relay/src/lib/eth.ts (hunk 2 above)
Comment (AlfredoG87) [reply packages/relay/src/lib/eth.ts]: ✅ Done

**Review by Nana-EC — APPROVED** [review]
LGTM
