### PR TITLE
fix: Allow the HBar Rate Limiter to be disabled.

### LINKED ISSUE #3251: HBar Rate Limiter should have the ability to be disabled.
### Description

As a relay operator I should have the ability to disable all HBar Rate Limiting.

### Steps to reproduce

Currently not available, but it was.  As a workaround the spending tiers can have high values set.

### Additional context

_No response_

### Hedera network

mainnet

### Version

v0.59.0

### Operating system

Linux

### PR DESCRIPTION
**Pull request by ebadiere**
This fix allows the HBar Rate Limiter to be disabled by setting the `HBAR_RATE_LIMIT_TINYBAR` to `0`

**Related issue(s)**:

Fixes #3251 

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

### CODE REVIEW

File: packages/relay/src/lib/constants.ts [hunk 1]
```diff
@@ -145,7 +145,7 @@ export default {
   // @ts-ignore
   HBAR_RATE_LIMIT_DURATION: parseInt(ConfigService.get('HBAR_RATE_LIMIT_DURATION') || '86400000'), // 1 day
   // @ts-ignore
-  HBAR_RATE_LIMIT_TOTAL: BigNumber(ConfigService.get('HBAR_RATE_LIMIT_TINYBAR') || '800000000000'), // 8000 HBARs
+  HBAR_RATE_LIMIT_TOTAL: BigNumber(ConfigService.get('HBAR_RATE_LIMIT_TINYBAR') ?? '800000000000'), // 8000 HBARs
```
Comment (Nana-EC) [inline packages/relay/src/lib/constants.ts:148]: Q: why this change and does it affect all the other configs?

File: packages/relay/src/lib/services/hbarLimitService/index.ts [hunk 2]
```diff
@@ -90,6 +96,10 @@ export class HbarLimitService implements IHbarLimitService {
     this.reset = this.getResetTimestamp();
     this.remainingBudget = this.totalBudget;
 
+    if (this.remainingBudget.toTinybars().isZero()) {
```
Comment (Nana-EC) [inline packages/relay/src/lib/services/hbarLimitService/index.ts:99]: nit: as a guard I'd say zero or less

File: packages/relay/tests/lib/services/hbarLimitService/hbarLimitService.spec.ts [hunk 3]
```diff
@@ -494,6 +494,29 @@ describe('HBAR Rate Limit Service', function () {
...
+        ethAddressHbarSpendingPlanRepositoryStub,
+        ipAddressHbarSpendingPlanRepositoryStub,
+        logger,
+        register,
+        Hbar.fromTinybars(0),
+        limitDuration,
+      );
+      it('should return false if the rate limiter is disabled by setting HBAR_RATE_LIMIT_TINYBAR to zero', async function () {
+        // hbarLimitServiceDisabled.disableRateLimiter();
+        const result = await hbarLimitServiceDisabled.shouldLimit(
```
Comment (Nana-EC) [inline packages/relay/tests/lib/services/hbarLimitService/hbarLimitService.spec.ts:510]: This actually doesn't really test that the rate limiter is working.
For instance if a future code change was made and the return was false for some other reason that a 0 value this logic would not catch it.
I think we should reconsider the layout on the product side.

File: packages/relay/src/lib/services/hbarLimitService/index.ts [hunk 4]
```diff
@@ -181,6 +191,10 @@ export class HbarLimitService implements IHbarLimitService {
     requestDetails: RequestDetails,
     estimatedTxFee: number = 0,
   ): Promise<boolean> {
+    if (this.disableRateLimiter) {
```
Comment (Nana-EC) [inline packages/relay/src/lib/services/hbarLimitService/index.ts:194]: I would suggest adding an `isEnabled()` function to `IHbarLimitService`.
Then this method can call it and it can be tested.

**Review by Nana-EC — COMMENTED** [review]
Good approach. 
Question on the config changes.
Also I provided a suggestion to be a bit more strict

File: packages/relay/src/lib/constants.ts (hunk 1 above)
Comment (ebadiere) [reply packages/relay/src/lib/constants.ts:148]: While working on the acceptance test I noticed that the zero value for the `HBAR_RATE_LIMIT_TINYBAR` was not getting picked up.  Most likely because the logical OR operator `||` returns the first truthy value and 0 is falsy.  The nullish coalescing operator `??` falls back to the default value when the left-hand operand is `null` or `undefined`, not when it's `0` or any other falsy value.

File: packages/server/tests/acceptance/hbarLimiter.spec.ts [hunk 5]
```diff
@@ -887,5 +914,77 @@ describe('@hbarlimiter HBAR Limiter Acceptance Tests', function () {
         });
       });
     });
+
+    describe('@hbarlimiter-batch3 BASIC Tier', () => {
```
[the remark this answers is not in the document]
Comment (ebadiere) [reply packages/server/tests/acceptance/hbarLimiter.spec.ts:918]: I had to add it to another branch because of the order of loading environment variables in the acceptance tests.  The `relay.ts` reads and sets the `HBAR_RATE_LIMIT_TINYBAR` at boot time.

[the remark this answers is not in the document]
Comment (quiet-node) [reply packages/server/tests/acceptance/hbarLimiter.spec.ts:918]: I believe he is addressing the scenario in which the limiter is turned off, allowing an account to make calls without being HBAR rate limited.

@ebadiere, if that's true and the suite is needed, I suggest renaming the test suite from "BASIC Tier" to something more descriptive, such as "Unlimited Limit" or "Limiter Off" or something like that. The term "BASIC Tier" is confusing, as we have another suite with the same name.

File: packages/server/tests/acceptance/hbarLimiter.spec.ts [hunk 6]
```diff
@@ -887,5 +914,77 @@ describe('@hbarlimiter HBAR Limiter Acceptance Tests', function () {
...
+            hbarSpendingPlan = await hbarSpendingPlanRepository.findByIdWithDetails(
+              ethSpendingPlan.planId,
+              requestDetails,
+            );
+          }
+
+          await pollForProperAmountSpent(hbarSpendingPlan, deploymentCounts + 1, expectedTxCost);
+        }
+        // Verify that the amount spent exceeds the HBAR limit
+        const amountSpent = await pollForProperAmountSpent(hbarSpendingPlan, deploymentCounts, expectedTxCost);
```
Comment (quiet-node) [inline packages/server/tests/acceptance/hbarLimiter.spec.ts:978]: after the loop hbarSpendingPlan can still be null in cases that no loop has got through. Please add this block above this line so the null error can be discarded
```typescript
      if (!hbarSpendingPlan) {
             const ethSpendingPlan = await ethAddressSpendingPlanRepository.findByAddress(
             accounts[2].wallet.address,
             requestDetails,
             );
             hbarSpendingPlan = await hbarSpendingPlanRepository.findByIdWithDetails(
                 ethSpendingPlan.planId,
                 requestDetails,
        );
     }
```

File: packages/server/tests/acceptance/hbarLimiter.spec.ts [hunk 7]
```diff
@@ -887,5 +914,77 @@ describe('@hbarlimiter HBAR Limiter Acceptance Tests', function () {
...
+        expect(amountSpent).to.be.gte(maxBasicSpendingLimit);
+
+        // Verify that remaining HBAR limit is zero or negative
+        const remainingHbarsAfter = Number(await metrics.get(testConstants.METRICS.REMAINING_HBAR_LIMIT));
+        expect(remainingHbarsAfter).to.be.lte(0);
+
+        // Confirm that deployments continued even after the limit was exhausted
+        expect(deploymentCounts).to.be.gte(1);
```
Comment (quiet-node) [inline packages/server/tests/acceptance/hbarLimiter.spec.ts:986]: Just an extra proof saying that the account can still make calls
```typescript
await expect(deployContract(largeContractJson, same_account.wallet)).to.be.fulfilled;
```

File: packages/server/tests/acceptance/hbarLimiter.spec.ts [hunk 8]
```diff
@@ -887,5 +914,77 @@ describe('@hbarlimiter HBAR Limiter Acceptance Tests', function () {
...
+        logger.info(`${requestDetails.formattedRequestId} Creating accounts`);
+        logger.info(
+          `${requestDetails.formattedRequestId} HBAR_RATE_LIMIT_TINYBAR: ${ConfigService.get(
+            'HBAR_RATE_LIMIT_TINYBAR',
+          )}`,
+        );
+
+        const initialAccount: AliasAccount = global.accounts[0];
+
+        const neededAccounts: number = 3;
```
Comment (quiet-node) [inline packages/server/tests/acceptance/hbarLimiter.spec.ts:931]: might have missed it but it doesn't seem to need that many alias accounts. Maybe just one account is good enough.

File: packages/server/tests/acceptance/hbarLimiter.spec.ts [hunk 9]
```diff
@@ -887,5 +914,77 @@ describe('@hbarlimiter HBAR Limiter Acceptance Tests', function () {
...
+        const basicPlans = await hbarSpendingPlanRepository.findAllActiveBySubscriptionTier(
+          [SubscriptionTier.BASIC],
+          requestDetails,
+        );
+        for (const plan of basicPlans) {
+          await hbarSpendingPlanRepository.delete(plan.id, requestDetails);
+          await ethAddressSpendingPlanRepository.deleteAllByPlanId(plan.id, 'before', requestDetails);
+          await ipSpendingPlanRepository.deleteAllByPlanId(plan.id, 'before', requestDetails);
+        }
+      });
```
Comment (quiet-node) [inline packages/server/tests/acceptance/hbarLimiter.spec.ts:951]: Correct me if I'm wrong but the plans might not need to be reset. It was for something special tested in batch1 BASIC tier.

File: packages/server/tests/acceptance/hbarLimiter.spec.ts [hunk 10]
```diff
@@ -887,5 +914,77 @@ describe('@hbarlimiter HBAR Limiter Acceptance Tests', function () {
...
+    describe('@hbarlimiter-batch3 BASIC Tier', () => {
+      const accounts: AliasAccount[] = [];
+
+      beforeEach(async function () {
+        logger.info(`${requestDetails.formattedRequestId} Creating accounts`);
+        logger.info(
+          `${requestDetails.formattedRequestId} HBAR_RATE_LIMIT_TINYBAR: ${ConfigService.get(
+            'HBAR_RATE_LIMIT_TINYBAR',
+          )}`,
+        );
```
Comment (quiet-node) [inline packages/server/tests/acceptance/hbarLimiter.spec.ts:927]: Since this suite provides coverage when the limiter is off, there should likely be assertions confirming that `HBAR_RATE_LIMIT_TINYBAR` is set to 0 and that `isDisable` is set to true. For example, we could include an assertion like `expect(HBAR_RATE_LIMIT_TINYBAR).to.eq(0)`. If it's feasible to access `isDisable`, we could also add an assertion for that as well (not sure if the isDisable is reachable tho)

File: package.json [hunk 11]
```diff
@@ -50,6 +50,7 @@
     "acceptancetest:ratelimiter": "nyc ts-mocha packages/ws-server/tests/acceptance/index.spec.ts -g '@web-socket-ratelimiter' --exit && ts-mocha packages/server/tests/acceptance/index.spec.ts -g '@ratelimiter' --exit",
     "acceptancetest:hbarlimiter_batch1": "HBAR_RATE_LIMIT_BASIC=1000000000 HBAR_RATE_LIMIT_EXTENDED=1500000000 HBAR_RATE_LIMIT_PRIVILEGED=2000000000 nyc ts-mocha packages/server/tests/acceptance/index.spec.ts -g '@hbarlimiter-batch1' --exit",
     "acceptancetest:hbarlimiter_batch2": "HBAR_RATE_LIMIT_BASIC=1000000000 HBAR_RATE_LIMIT_EXTENDED=1500000000 HBAR_RATE_LIMIT_PRIVILEGED=2000000000 nyc ts-mocha packages/server/tests/acceptance/index.spec.ts -g '@hbarlimiter-batch2' --exit",
+    "acceptancetest:hbarlimiter_batch3": "HBAR_RATE_LIMIT_TINYBAR=0 HBAR_RATE_LIMIT_BASIC=1000000000 HBAR_RATE_LIMIT_EXTENDED=1500000000 HBAR_RATE_LIMIT_PRIVILEGED=2000000000 nyc ts-mocha packages/server/tests/acceptance/index.spec.ts -g '@hbarlimiter-batch3' --exit",
```
Comment (quiet-node) [inline package.json:53]: This will need to be added in the workflow as well so it can be shown in the CI board

File: packages/relay/tests/lib/services/hbarLimitService/hbarLimitService.spec.ts (hunk 3 above)
Comment (ebadiere) [reply packages/relay/tests/lib/services/hbarLimitService/hbarLimitService.spec.ts:519]: Updated test to include a condition that would normally trigger rate limiting, but verifies that `shouldLimit` returns false since rate limiting is not enabled.

File: packages/relay/src/lib/services/hbarLimitService/index.ts (hunk 2 above)
Comment (ebadiere) [reply packages/relay/src/lib/services/hbarLimitService/index.ts]: Done.

File: packages/relay/src/lib/services/hbarLimitService/index.ts (hunk 4 above)
Comment (ebadiere) [reply packages/relay/src/lib/services/hbarLimitService/index.ts]: Done.

File: packages/server/tests/acceptance/hbarLimiter.spec.ts (hunk 8 above)
Comment (ebadiere) [reply packages/server/tests/acceptance/hbarLimiter.spec.ts:931]: Yes, one is good enough.

File: packages/server/tests/acceptance/hbarLimiter.spec.ts (hunk 9 above)
Comment (ebadiere) [reply packages/server/tests/acceptance/hbarLimiter.spec.ts:951]: You are correct. Initially, I observed some instability when running the tests. To address this, I thought that clearing out the repositories—so that the spending plans would be recreated during the contract deployments—would provide a deterministic solution. However, after removing the code that cleared the repositories and running the tests multiple times, I achieved consistent results, indicating that the instability was unrelated to the repository state.

File: packages/server/tests/acceptance/hbarLimiter.spec.ts (hunk 5 above)
[the remark this answers is not in the document]
Comment (ebadiere) [reply packages/server/tests/acceptance/hbarLimiter.spec.ts]: @quiet-node Done.

File: packages/server/tests/acceptance/hbarLimiter.spec.ts [hunk 12]
```diff
@@ -57,6 +57,33 @@ import mediumSizeContract from '../contracts/hbarLimiterContracts/mediumSizeCont
 config({ path: resolve(__dirname, '../localAcceptance.env') });
 const DOT_ENV = dotenv.parse(fs.readFileSync(resolve(__dirname, '../localAcceptance.env')));
 
+const pollForProperAmountSpent = async (
```
[the remark this answers is not in the document]
Comment (ebadiere) [reply packages/server/tests/acceptance/hbarLimiter.spec.ts]: Done.

File: packages/server/tests/acceptance/hbarLimiter.spec.ts (hunk 6 above)
Comment (ebadiere) [reply packages/server/tests/acceptance/hbarLimiter.spec.ts:958]: Done.

File: packages/server/tests/acceptance/hbarLimiter.spec.ts (hunk 7 above)
Comment (ebadiere) [reply packages/server/tests/acceptance/hbarLimiter.spec.ts:966]: Done.

File: packages/server/tests/acceptance/hbarLimiter.spec.ts (hunk 8 above)
Comment (ebadiere) [reply packages/server/tests/acceptance/hbarLimiter.spec.ts]: Done.

File: package.json (hunk 11 above)
Comment (ebadiere) [reply package.json:53]: Done.

File: packages/server/tests/acceptance/hbarLimiter.spec.ts (hunk 10 above)
Comment (ebadiere) [reply packages/server/tests/acceptance/hbarLimiter.spec.ts:900]: I added ` expect(ConfigService.get('HBAR_RATE_LIMIT_TINYBAR')).to.eq(0);` to the test.  I don't think it's easily feasible to check `isEnabled()` from an acceptance test.  The running instance of the `HBarRateLimiter` would have to be captured in the server package This is covered in the unit test in the relay.

File: packages/server/tests/acceptance/hbarLimiter.spec.ts [hunk 13]
```diff
@@ -887,5 +887,85 @@ describe('@hbarlimiter HBAR Limiter Acceptance Tests', function () {
...
+            neededAccounts,
+            initialBalance,
+            requestDetails,
+          )),
+        );
+        global.accounts.push(...accounts);
+        const basicPlans = await hbarSpendingPlanRepository.findAllActiveBySubscriptionTier(
+          [SubscriptionTier.BASIC],
+          requestDetails,
+        );
```
[the remark this answers is not in the document]
Comment (ebadiere) [reply packages/server/tests/acceptance/hbarLimiter.spec.ts:918]: Correct, thanks.  Removed.

File: packages/server/tests/acceptance/hbarLimiter.spec.ts [hunk 14]
```diff
@@ -887,5 +887,85 @@ describe('@hbarlimiter HBAR Limiter Acceptance Tests', function () {
...
+        const neededAccounts: number = 1;
+        accounts.push(
+          ...(await Utils.createMultipleAliasAccounts(
+            mirrorNode,
+            initialAccount,
+            neededAccounts,
+            initialBalance,
+            requestDetails,
+          )),
+        );
```
[the remark this answers is not in the document]
Comment (ebadiere) [reply packages/server/tests/acceptance/hbarLimiter.spec.ts]: Yes.  Removed and just using `global.accounts[0]`.  Thanks.

File: packages/relay/src/lib/services/hbarLimitService/index.ts [hunk 15]
```diff
@@ -142,6 +152,14 @@ export class HbarLimitService implements IHbarLimitService {
...
   }
 
+  /**
+   * Checks if the rate limiter is enabled.
+   * returns {boolean} - `true` if the rate limiter is enabled, otherwise `false`.
+   */
+  isEnabled(): boolean {
+    return !this.disableRateLimiter;
+  }
+
```
[the remark this answers is not in the document]
Comment (ebadiere) [reply packages/relay/src/lib/services/hbarLimitService/index.ts:162]: This was recommended by @Nana-EC in one of the earlier comments.  It makes sense to me.

File: packages/relay/src/lib/services/hbarLimitService/index.ts [hunk 16]
```diff
@@ -37,6 +37,12 @@ export class HbarLimitService implements IHbarLimitService {
     PRIVILEGED: Hbar.fromTinybars(constants.HBAR_RATE_LIMIT_PRIVILEGED),
   };
 
+  /**
+   * Disables the rate limiter.
```
[the remark this answers is not in the document]
Comment (ebadiere) [reply packages/relay/src/lib/services/hbarLimitService/index.ts]: Updated comments to be more descriptive.

File: packages/relay/src/lib/services/hbarLimitService/index.ts (hunk 15 above)
[the remark this answers is not in the document]
Comment (Nana-EC) [reply packages/relay/src/lib/services/hbarLimitService/index.ts:162]: Yeah, I think it's cleaner interface wise also since the service isn't required to be on. I'm open to debate

File: packages/relay/src/lib/services/hbarLimitService/IHbarLimitService.ts [hunk 17]
```diff
@@ -31,4 +31,5 @@ export interface IHbarLimitService {
     estimatedTxFee?: number,
   ): Promise<boolean>;
   addExpense(cost: number, ethAddress: string, requestDetails: RequestDetails, ipAddress?: string): Promise<void>;
+  isEnabled(): boolean;
```
[the remark this answers is not in the document]
Comment (Nana-EC) [reply packages/relay/src/lib/services/hbarLimitService/IHbarLimitService.ts:34]: Yeah see https://github.com/hashgraph/hedera-json-rpc-relay/pull/3252#discussion_r1841253642

File: packages/server/tests/acceptance/hbarLimiter.spec.ts (hunk 13 above)
[the remark this answers is not in the document]
Comment (ebadiere) [reply packages/server/tests/acceptance/hbarLimiter.spec.ts]: Removed.

**Review by mishomihov00 — APPROVED** [review]
Reviewed and approved only this file:
`.github/workflows/acceptance.yml`

File: packages/relay/src/lib/services/hbarLimitService/index.ts [hunk 18]
```diff
@@ -90,6 +96,10 @@ export class HbarLimitService implements IHbarLimitService {
     this.reset = this.getResetTimestamp();
     this.remainingBudget = this.totalBudget;
 
+    if (this.remainingBudget.toTinybars().lte(0)) {
+      this.disableRateLimiter = true;
+    }
```
Comment (victor-yanev) [inline packages/relay/src/lib/services/hbarLimitService/index.ts:101]:
```suggestion
    if (this.totalBudget.toTinybars().lte(0)) {
      this.disableRateLimiter = true;
    }
```

File: packages/relay/src/lib/services/hbarLimitService/index.ts [hunk 19]
```diff
@@ -181,6 +199,10 @@ export class HbarLimitService implements IHbarLimitService {
     requestDetails: RequestDetails,
     estimatedTxFee: number = 0,
   ): Promise<boolean> {
+    if (!this.isEnabled()) {
+      return false;
+    }
```
Comment (victor-yanev) [inline packages/relay/src/lib/services/hbarLimitService/index.ts:204]: Please, add this check to `addExpense` as well:
```typescript
async addExpense(cost: number, ethAddress: string, requestDetails: RequestDetails): Promise<void> {
  if (!this.isEnabled()) {
    return;
  }
  ...
}
```

Comment (ebadiere) [reply packages/relay/src/lib/services/hbarLimitService/index.ts:204]: Done.

File: packages/relay/src/lib/services/hbarLimitService/index.ts (hunk 18 above)
Comment (ebadiere) [reply packages/relay/src/lib/services/hbarLimitService/index.ts]: Done

File: packages/relay/src/lib/services/hbarLimitService/index.ts (hunk 15 above)
[the remark this answers is not in the document]
Comment (quiet-node) [reply packages/relay/src/lib/services/hbarLimitService/index.ts:162]: Ah I see yeah a getter is good in terms of encapsulation and readability. Thanks for the explanation!

File: packages/server/tests/acceptance/hbarLimiter.spec.ts [hunk 20]
```diff
@@ -887,5 +887,67 @@ describe('@hbarlimiter HBAR Limiter Acceptance Tests', function () {
         });
       });
     });
+
+    describe('@hbarlimiter-batch3 Unlimited', () => {
+      const accounts: AliasAccount[] = [];
```
[the remark this answers is not in the document]
Comment (ebadiere) [reply packages/server/tests/acceptance/hbarLimiter.spec.ts]: Done.

File: packages/server/tests/acceptance/hbarLimiter.spec.ts [hunk 21]
```diff
@@ -887,5 +887,67 @@ describe('@hbarlimiter HBAR Limiter Acceptance Tests', function () {
...
+
+      beforeEach(async function () {
```
[the remark this answers is not in the document]
Comment (ebadiere) [reply packages/server/tests/acceptance/hbarLimiter.spec.ts]: Done.

**Review by quiet-node — APPROVED** [review]

File: packages/relay/src/lib/constants.ts (hunk 1 above)
Comment (Nana-EC) [reply packages/relay/src/lib/constants.ts:148]: Nice catch.
Can you make a note here on that. Also i think you should open a quick issue to note that all integer numbers will hit this issue so we should do a quick check and see if there are other items that need to be fixed in a separate PR

**Review by Nana-EC — APPROVED** [review]
LG, see note on config issue to open

**Review by quiet-node — APPROVED** [review]
LGTM! Great work!

**Review by Nana-EC — APPROVED** [review]

**Review by victor-yanev — APPROVED** [review]
