### PR TITLE
fix: captured transactionFee in metrics and HBAR limiter class in executeTransaction and deleteFile

### LINKED ISSUE #2707: HBAR Burned Rate is not captured in executeTransaction() and deleteFile()
### Problem

Currently, the operator gets charged when an eth_sendRawTransaction is submitted. This process involves many transactions by the SDK, and each transacction would cost a different amount of HBAR. So far, there are four main transactions: FileCreate, FileAppend, ExecuteTransaction, and FileDelete. While charged HBAR is correctly added to metrics in FileCreate and FileAppend, the cost has not been captured in ExecuteTransaction and FileDelete.

### Solution

Add the HBAR to metrics and HBAR rate limitter class for ExecuteTransaction and FileDelete

### Alternatives

_No response_

### PR DESCRIPTION
**Pull request by quiet-node**
**Description**:
This PR is a hotfix for v0.51 that added steps to capture transactionFee in metrics and HBAR limiter class for executeTransaction and deleteFile.

To retrieve the `transactionFee` in `executeTransaction()`, the `getRecord()` method was utilized. The `getRecord()` method exposes and throws errors caused by invalid transactions on the network, which were previously ignored. These errors were typically discovered only after repeated lookups on the mirror node, with `MIRROR_NODE_GET_CONTRACT_RESULTS_RETRIES` (10) multiplied by `MIRROR_NODE_RETRY_DELAY` (2000ms), resulting in a total of 20000ms (20 seconds). This error exposure helps to reduce transaction time and ensures more accurate and secure handling of transactions.

This PR also tweaked and reused `executeGetTransactionRecord()` method to capture transactionFee of EthereumTransactions and add the fees to metrics and HBAR rate limiter class.

**Related issue(s)**:

Fixes #2707 

**Notes for reviewer**:

**Checklist**

- [x] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

### CODE REVIEW

File: packages/relay/src/lib/clients/sdkClient.ts [hunk 1]
```diff
@@ -468,19 +468,68 @@ export class SDKClient {
...
+
+        // get transactionFee and gasUsed for metrics
+        /**
+         * @todo: Determine how to separate the fee charged exclusively by the operator because
+         *        the transactionFee below includes the entire charges of the transaction,
+         *        with some portions paid by tx.from, not the operator.
+         */
+        transactionFee = transactionRecord.transactionFee.toTinybars().toNumber();
+        gasUsed = transactionRecord?.contractFunctionResult?.gasUsed.toNumber();
+      } catch (e: any) {
```
Comment (Nana-EC) [inline packages/relay/src/lib/clients/sdkClient.ts:493]: Q: why the catch?
There's already a larger catch that should handle any transaction execution failures

File: packages/relay/src/lib/clients/sdkClient.ts [hunk 2]
```diff
@@ -468,19 +468,68 @@ export class SDKClient {
...
     try {
-      const shouldLimit = this.hbarLimiter.shouldLimit(currentDateNow, SDKClient.transactionMode, callerName);
-      if (shouldLimit) {
+      if (this.hbarLimiter.shouldLimit(currentDateNow, SDKClient.transactionMode, callerName))
         throw predefined.HBAR_RATE_LIMIT_EXCEEDED;
-      }
 
       this.logger.info(`${requestIdPrefix} Execute ${transactionType} transaction`);
-      const resp = await transaction.execute(this.clientMain);
+      const transactionResponse = await transaction.execute(this.clientMain);
```
Comment (Nana-EC) [inline packages/relay/src/lib/clients/sdkClient.ts:479]: Q: Are you just extracting `executeGetTransactionRecord()`?
Why not just call it here as all this logic is already covered?
No longer calling `executeGetTransactionRecord()` was a regression.
```suggestion
      const transactionResponse = await transaction.execute(this.clientMain);
      executeGetTransactionRecord(transactionResponse, transactionType, callerName, interactingEntity, requestId);
```

**Review by Nana-EC — COMMENTED** [review]
Curious why we don't just revert the regression and utilize `executeGetTransactionRecord()`

File: packages/relay/src/lib/clients/sdkClient.ts (hunk 2 above)
Comment (quiet-node) [reply packages/relay/src/lib/clients/sdkClient.ts:473]: Updated with new changes. `executeGetTransactionRecord()` is now tweaked and reused.

File: packages/relay/src/lib/clients/sdkClient.ts (hunk 1 above)
Comment (quiet-node) [reply packages/relay/src/lib/clients/sdkClient.ts]: updated with new changes.

**Review by georgi-l95 — APPROVED** [review]

File: packages/relay/src/lib/clients/sdkClient.ts [hunk 3]
```diff
@@ -469,18 +469,21 @@ export class SDKClient {
     const requestIdPrefix = formatRequestIdMessage(requestId);
     const currentDateNow = Date.now();
     try {
-      const shouldLimit = this.hbarLimiter.shouldLimit(currentDateNow, SDKClient.transactionMode, callerName);
```
[the remark this answers is not in the document]
Comment (quiet-node) [reply packages/relay/src/lib/clients/sdkClient.ts:472]: oh yeah you're right that makes sense I removed this as I thought it was already added in the `executeGetTransactionRecord()` but we should definitely check it before execute the transaction. Reverted.

**Review by ebadiere — APPROVED** [review]

**Review by Nana-EC — APPROVED** [review]
