### PR TITLE
fix: removed chainId field for legacy EIP155 transactions (#2468)

### LINKED ISSUE #2468: Wrong formatting of pre-EIP155 transactions
### Description

When an unprotected transaction (pre-EIP155) is returned by the relay using `eth_getTransactionByHash` for example a `chain_id` property of `0x` is returned which results in incompatibility with certain tooling (for example foundry).
The proper behavior is to return a transaction object without a `chain_id` property.

### Steps to reproduce

1. Start the relay
2. Broadcast an unprotected transaction for example
```bash
cast publish --rpc-url http://localhost:7546/ 0xf8a58085174876e800830186a08080b853604580600e600039806000f350fe7fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffe03601600081602082378035828234f58015156039578182fd5b8082525050506014600cf31ba02222222222222222222222222222222222222222222222222222222222222222a02222222222222222222222222222222222222222222222222222222222222222 
```

### Additional context

_No response_

### Hedera network

other

### Version

v0.47.0

### Operating system

None

### PR DESCRIPTION
**Pull request by quiet-node**
**Description**:
This PR simply remove the chainId field if the transaction result is a legacy EIP155 transaction whose chainId equals to "0x".

**Related issue(s)**:

Fixes #2468

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

### CODE REVIEW

File: packages/relay/src/formatters.ts [hunk 1]
```diff
@@ -147,7 +147,7 @@ const formatContractResult = (cr: any) => {
   const commonFields = {
     blockHash: toHash32(cr.block_hash),
     blockNumber: nullableNumberTo0x(cr.block_number),
-    chainId: cr.chain_id,
+    chainId: cr.chain_id === '0x' ? undefined : cr.chain_id,
```
Comment (Nana-EC) [inline packages/relay/src/formatters.ts:150]: Missing UT

**Review by Nana-EC — CHANGES_REQUESTED** [review]
Looks good.
Nice acceptance tests but there's a missing unit test.

**Review by AlfredoG87 — DISMISSED** [review]
LGTM

File: packages/relay/src/formatters.ts (hunk 1 above)
Comment (quiet-node) [reply packages/relay/src/formatters.ts]: updated

File: packages/server/tests/acceptance/rpc_batch1.spec.ts [hunk 2]
```diff
@@ -1211,13 +1231,13 @@ describe('@api-batch-1 RPC Server Acceptance Tests', function () {
         const transaction = {
           type: 2,
           chainId: Number(CHAIN_ID),
-          nonce: await relay.getAccountNonce(accounts[2].address, requestId),
+          nonce: await relay.getAccountNonce(accounts[1].address, requestId),
```
Comment (quiet-node) [inline packages/server/tests/acceptance/rpc_batch1.spec.ts:1234]: note for reviewer: since accounts[2] is the payers of most of the test, when it reaches this case, system throws Insufficient Fund error. Therefore, this change is made to update the payer to account[1] for this case.

**Review by ebadiere — DISMISSED** [review]
LG.

File: packages/relay/src/formatters.ts [hunk 3]
```diff
@@ -147,7 +147,7 @@ const formatContractResult = (cr: any) => {
   const commonFields = {
     blockHash: toHash32(cr.block_hash),
     blockNumber: nullableNumberTo0x(cr.block_number),
-    chainId: cr.chain_id,
+    chainId: cr.chain_id === EMPTY_HEX ? undefined : cr.chain_id,
```
Comment (Nana-EC) [inline packages/relay/src/formatters.ts:150]: nit: add a comment on what this does and why so other devs understand

**Review by Nana-EC — COMMENTED** [review]
LG. One nit on comment

**Review by Nana-EC — DISMISSED** [review]

**Review by AlfredoG87 — APPROVED** [review]
LGTM
