### PR TITLE
fix: Adds null check for param in validation

### LINKED ISSUE #2376: "Error raised during getCode for address null" is not returned in the response to the client and can cause confusion.
### Description

"Unknown error invoking RPC" is returned to the client when in the logs we see "Error raised during getCode for address null".     The "address is null" message should be returned to the client to give the user an idea of what is going on.

### Steps to reproduce

1. Run `eth_getCode` with a null address value.

### Additional context

_No response_

### Hedera network

mainnet

### Version

v0.45.2

### Operating system

Linux

### PR DESCRIPTION
**Pull request by konstantinabl**
**Description**:
Currently, when we pass null as a param for getCode or any other endpoint, we do not return a descriptive response to the user. Thus, this PR adds a check in the validator, that throws an error when the param passed is null.

**Files Changed** :

1. `src/validator/utils.ts` - Added a null check for the parameters
2. `rpc_batch2.spec.ts` - Fixed few failing tests

**Type of Change**:
  - [x] Bug fix
  - [ ] New feature
  - [ ] Breaking change
  - [ ] Documentation update
  - [ ] Refactoring

**Related issue(s)**:
Fixes #2376

### CODE REVIEW

File: packages/server/src/validator/utils.ts [hunk 1]
```diff
@@ -14,7 +14,11 @@ export function validateParam(index: number | string, param: any, validation: an
     throw predefined.MISSING_REQUIRED_PARAMETER(index);
   }
 
-  if (param != null && Array.isArray(paramType)) {
+  if (param === null) {
+    throw predefined.INVALID_PARAMETER(index, `The value passed is not valid: ${param}.`);
+  }
+
+  if (param !== undefined && Array.isArray(paramType)) {
```
Comment (victor-yanev) [inline packages/server/src/validator/utils.ts:21]: Why are we allowing `undefined` as a parameter, but not `null`?

File: packages/server/src/validator/utils.ts [hunk 2]
```diff
@@ -14,7 +14,11 @@ export function validateParam(index: number | string, param: any, validation: an
     throw predefined.MISSING_REQUIRED_PARAMETER(index);
   }
 
-  if (param != null && Array.isArray(paramType)) {
+  if (param === null) {
+    throw predefined.INVALID_PARAMETER(index, `The value passed is not valid: ${param}.`);
```
Comment (georgi-l95) [inline packages/server/src/validator/utils.ts:18]: Hm, I think that according to the official schema, everything different than a string contating 20 byte hex should be rejected with this error. wdyt ?

Comment (victor-yanev) [reply packages/server/src/validator/utils.ts:18]: Do we want to throw this validation error even for parameters which are not required? It doesn't seem right.

If not, we can change `requiredIsMissing(param, validation.required)` which is already called above to also take `null` values into account:

```diff
export function requiredIsMissing(param: any, required: boolean) {
- return required && param === undefined;
+ return required && (param === undefined || param === null);
}
```

File: packages/server/tests/acceptance/rpc_batch2.spec.ts [hunk 3]
```diff
@@ -976,12 +976,13 @@ describe('@api-batch-2 RPC Server Acceptance Tests', function () {
       const signedTx = await accounts[1].wallet.signTransaction(transaction);
       const transactionHash = await relay.sendRawTransaction(signedTx, requestId);
 
-      const blockNumber = await relay.call(
+      const transactionResult = await relay.call(
```
Comment (victor-yanev) [inline packages/server/tests/acceptance/rpc_batch2.spec.ts:979]: `transactionResult` -> `receipt` or `transactionReceipt`

File: packages/server/tests/acceptance/rpc_batch2.spec.ts [hunk 4]
```diff
@@ -1021,11 +1022,13 @@ describe('@api-batch-2 RPC Server Acceptance Tests', function () {
       const signedTx = await accounts[1].wallet.signTransaction(transaction);
       const transactionHash = await relay.sendRawTransaction(signedTx, requestId);
 
-      const blockHash = await relay.call(
+      const transactionResult = await relay.call(
```
Comment (victor-yanev) [inline packages/server/tests/acceptance/rpc_batch2.spec.ts:1025]: nit: Same here

File: packages/server/src/validator/utils.ts (hunk 2 above)
Comment (konstantinabl) [reply packages/server/src/validator/utils.ts:18]: > Hm, I think that according to the official schema, everything different than a string contating 20 byte hex should be rejected with this error. wdyt ?

@georgi-l95 do you mean in general? or for getcode in particular?

File: packages/server/src/validator/utils.ts (hunk 1 above)
Comment (konstantinabl) [reply packages/server/src/validator/utils.ts]: Null is allowed only for to address in transaction objects and filter objects, which is cerified in the if below, so it makes sense that any other param equal to null should not be allowed. Undefined is allowed for unrequired params, so I've changed the logic a little bit to check it above in an else after the check for requiredIsMissing

File: packages/server/src/validator/utils.ts (hunk 2 above)
Comment (konstantinabl) [reply packages/server/src/validator/utils.ts:22]: @georgi-l95  This file is executed for every parameter, thats why I have added param == null here

File: packages/server/src/validator/utils.ts [hunk 5]
```diff
@@ -27,7 +35,7 @@ export function validateParam(index: number | string, param: any, validation: an
     }
   }
 
-  if (param != null && !Array.isArray(paramType)) {
+  if (!Array.isArray(paramType)) {
     const result = isArray ? paramType.test(index, param, validation.type[1]) : paramType.test(param);
```
Comment (victor-yanev) [inline packages/server/src/validator/utils.ts:39]: We already know `isArray === false` here
```suggestion
    const result = : paramType.test(param);
```

**Review by victor-yanev — APPROVED** [review]
LGTM, just one small nit

File: packages/server/src/validator/utils.ts (hunk 5 above)
Comment (konstantinabl) [reply packages/server/src/validator/utils.ts]: Fixed it

File: packages/server/tests/integration/server.spec.ts [hunk 6]
```diff
@@ -2144,7 +2144,7 @@ describe('RPC Server', function () {
         }
       });
 
-      it('validates address filter', async function () {
+      it.only('validates address filter', async function () {
```
Comment (victor-yanev) [inline packages/server/tests/integration/server.spec.ts:2147]: remove `.only` from here

File: packages/server/src/validator/utils.ts [hunk 7]
```diff
@@ -12,9 +12,17 @@ export function validateParam(index: number | string, param: any, validation: an
 
   if (requiredIsMissing(param, validation.required)) {
     throw predefined.MISSING_REQUIRED_PARAMETER(index);
+  } else if (!validation.required && param === undefined) {
+    //if parameter is undefined and not required, no need to validate
+    //e.g estimateGas method, blockNumber is not required
+    return;
   }
```
Comment (victor-yanev) [inline packages/server/src/validator/utils.ts:19]: nit: this will be slightly easier to read:
```suggestion
  if (param === undefined) {
    if (validation.required) {
      throw predefined.MISSING_REQUIRED_PARAMETER(index);
    } else {
      // if parameter is undefined and not required, no need to validate
      // e.g estimateGas method, blockNumber is not required
      return;
    }
  }
```

**Review by victor-yanev — APPROVED** [review]
LGTM, I left two small suggestions:

**Review by victor-yanev — APPROVED** [review]

File: packages/server/src/validator/utils.ts (hunk 7 above)
Comment (konstantinabl) [reply packages/server/src/validator/utils.ts:19]: For some reason when I introduce the new change you suggested the unit tests start failing in the CI

**Review by victor-yanev — APPROVED** [review]

**Review by Ivo-Yankov — APPROVED** [review]
