### PR TITLE
Return 32 byte 0 on empty state_changes array

### LINKED ISSUE #732: Failed to send/recv `storage` err=GetStorage() when testing with Foundry
### Description

I have successfully set up Foundry to work with Hedera by configuring it to work with npm modules. We can run unit test, and complete fuzz testing. Github repo [here](https://github.com/a-ridley/hedera-smart-contract-testing-with-foundry).

The issue lies when attempting to use Foundry's fork testing to test against a smart contract that is deployed on testnet. In my test set up, I provided my smart contract's evm address (which I grabbed from hashscan).

Below is a snippet of my test set up.
```
function setUp() public {
        counter = Counter(0x0000000000000000000000000000000002Eba2A0);
        //counter.setNumber(0);
    }
```

The expected output is for my tests to run successfully. However, the result of running my tests gives the following error:

```
2022-12-01T18:28:36.945764Z ERROR sharedbackend: Failed to send/recv `storage` err=GetStorage(0x0000000000000000000000000000000002eba2a0, 0, 
(code: -32603, message: [Request ID: 6153887f-a84f-42e9-93c7-8fcb32047a21] Error invoking RPC: , data: None)) address=0x0000000000000000000000000000000002eba2a0 index=0

Running 1 test for test/foundry/Counter.t.sol:CounterTest
[FAIL. Reason: EvmError: FatalExternalError] testIncrement() (gas: 9223372036854754743)
Test result: FAILED. 0 passed; 1 failed; finished in 38.01s

Failing tests:
Encountered 1 failing test in test/foundry/Counter.t.sol:CounterTest
[FAIL. Reason: EvmError: FatalExternalError] testIncrement() (gas: 9223372036854754743)
```

### Steps to reproduce

1. Unzip the project below and open it in vscode
[simulate-swap-hedera.zip](https://github.com/hashgraph/hedera-json-rpc-relay/files/10137040/simulate-swap-hedera.zip)
2. edit the .env file
3. Open a terminal in the project's dir
4. run `HEDERA_RPC_URL=https://testnet.hashio.io/api `
5. run `forge test --fork-url $HEDERA_RPC_URL -vv --fork-block-number <block number>`

### Additional context

**note: block number needs to be at least 15 minutes in the past or you'll get the error below.**
`(code: -32007, message: [Request ID: 3804b205-6ef8-471d-92a2-e640d9131558] Historical balance data is available only after 15 minutes., data: None)) address=0x0000000000000000000000000000000002eba2a0`

### Hedera network

testnet

### Version

v2.18.5

### Operating system

macOS

### PR DESCRIPTION
**Pull request by lukelee-sl**
Signed-off-by: lukelee-sl <luke.lee@swirldslabs.com>

**Description**:
Return 32 byte 0 string when the returned state_changes array is empty.  This is similar behavior to other test chains.

**Related issue(s)**:

Fixes #732 

- [ ] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

### CODE REVIEW

File: packages/relay/src/lib/eth.ts [hunk 1]
```diff
@@ -499,13 +499,14 @@ export class EthImpl implements Eth {
       // retrieve the contract result details
       await this.mirrorNodeClient.getContractResultsDetails(address, contractResult.results[0].timestamp)
         .then(contractResultDetails => {
+          if(contractResultDetails === null) {
```
Comment (lukelee-sl) [inline packages/relay/src/lib/eth.ts:502]: we do want to do this null check here because we want to throw the RESOURCE_NOT_FOUND exception if the contract details are not found at all.

File: packages/relay/src/lib/eth.ts [hunk 2]
```diff
@@ -499,13 +499,14 @@ export class EthImpl implements Eth {
...
+            throw predefined.RESOURCE_NOT_FOUND(`Contract result details for contract address ${address} at timestamp=${contractResult.results[0].timestamp}`);
+          }
           if (EthImpl.isArrayNonEmpty(contractResultDetails?.state_changes)) {
             // filter the state changes to match slot and return value
             const stateChange = contractResultDetails.state_changes.find(stateChange => stateChange.slot === slot);
             result = stateChange.value_written;
-          } else {
```
Comment (lukelee-sl) [inline packages/relay/src/lib/eth.ts:506]: removing this else clause causes us to fall through to return the default 32byte 0 hex value.

**Review by Nana-EC — APPROVED** [review]
LG

File: packages/relay/src/lib/eth.ts (hunk 1 above)
Comment (david-bakin-sl) [reply packages/relay/src/lib/eth.ts:502]: BTW, now can lose the `?` on line 502 ...

Comment (lukelee-sl) [reply packages/relay/src/lib/eth.ts:502]: yes - nice catch

**Review by Nana-EC — APPROVED** [review]
