### PR TITLE
fix: reduce hbar limit only by operator fees

### LINKED ISSUE #2729: TransactionFee captured for executeTransaction has the total charged transaction fee in it, not just fees charged by Relay operator.
### Problem

The transactionFee captured for executeTransaction has the total charged transaction fee in it, not just fees charged by Relay operator.

### Solution

Figure out how to extract operator's charge from the total transactionFee

### Alternatives

_No response_

### PR DESCRIPTION
**Pull request by Ivo-Yankov**
**Description**:
This PR separates the transaction fee from the gas fee paid by the relay operator and the signer. Reduces the Hbar limiter only by the amount paid by the operator. This is done by traversing `transactionRecord.transfers` for the submitted EthereumTransaction.

Also adds a test that checks how much was the Hbar Limiter reduced after a large transaction, how much the operator has spent, the sum of all fees related to that transaction and compares those values. The test passes if the values are within 1% tolerance range from one another. The tolerated differance comes from fees from `.getRecord`, `.getReceipt`, etc.

**Related issue(s)**:

Fixes #2729 #2691 

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

### CODE REVIEW

File: packages/server/tests/helpers/assertions.ts [hunk 1]
```diff
@@ -458,4 +458,17 @@ export default class Assertions {
...
+   * Checks if the expected value is within a % range, relative to the actual value
+   * @param expected
+   * @param actual
+   * @param tolerance
+   */
+  static expectWithinTolerance(expected: number, actual: number, tolerance: number) {
+    global.logger.trace(`Expected: ${expected} ±${tolerance}`);
+    global.logger.trace(`Actual: ${expected}`);
+    expect(expected).to.be.gte(actual * (1 - tolerance));
+    expect(expected).to.be.lte(actual * (1 + tolerance));
```
Comment (victor-yanev) [inline packages/server/tests/helpers/assertions.ts:472]:
```suggestion
  static expectWithinTolerance(expected: number, actual: number, tolerance: number) {
    global.logger.trace(`Expected: ${expected} ±${tolerance}%`);
    global.logger.trace(`Actual: ${actual}`);
    const delta = tolerance * expected;
    expect(actual).to.be.approximately(expected, delta);
```

File: packages/server/tests/acceptance/hbarLimiter.spec.ts [hunk 2]
```diff
@@ -158,10 +164,69 @@ describe('@hbarlimiter HBAR Limiter Acceptance Tests', function () {
         await deployContract(mediumSizeContract, accounts[0].wallet);
 
         const remainingHbarsAfter = Number(await metrics.get(testConstants.METRICS.REMAINING_HBAR_LIMIT));
-        const expectedCost = 354819247;
+        const expectedCost = 331926551;
         verifyRemainingLimit(expectedCost, remainingHbarsBefore, remainingHbarsAfter);
       });
 
+      it('HBAR limiter is updated within acceptable tolerance range in relation to actual spent amount by the relay operator', async function () {
+        const TOLERANCE = 0.01;
```
Comment (victor-yanev) [inline packages/server/tests/acceptance/hbarLimiter.spec.ts:172]: 1% seems like a lot, can we try to reduce this to 0.1%?

```suggestion
        const TOLERANCE = 0.001;
```

File: packages/server/tests/acceptance/hbarLimiter.spec.ts [hunk 3]
```diff
@@ -158,10 +164,69 @@ describe('@hbarlimiter HBAR Limiter Acceptance Tests', function () {
...
+
+        await new Promise((r) => setTimeout(r, 3000));
```
Comment (victor-yanev) [inline packages/server/tests/acceptance/hbarLimiter.spec.ts:174]: QQ: Why are we waiting for 3 seconds here before we have done anything in the test?

File: packages/server/tests/acceptance/hbarLimiter.spec.ts [hunk 4]
```diff
@@ -158,10 +164,69 @@ describe('@hbarlimiter HBAR Limiter Acceptance Tests', function () {
...
+          )
+        ).transactions[0];
+        const fileCreateTimestamp = fileCreateTx.consensus_timestamp;
+        const fileAppendTxs = (
+          await mirrorNode.get(
+            `/transactions?order=desc&transactiontype=FILEAPPEND&account.id=${operatorAccount}&timestamp=gt:${fileCreateTimestamp}`,
+            requestId,
+          )
+        ).transactions;
+        expect(fileAppendTxs.length).to.eq(6);
```
Comment (victor-yanev) [inline packages/server/tests/acceptance/hbarLimiter.spec.ts:206]: Please, get this number dynamically by dividing the callData by the chunk size instead of hardcoding `6` as a value here.

File: packages/server/tests/acceptance/hbarLimiter.spec.ts [hunk 5]
```diff
@@ -158,10 +164,69 @@ describe('@hbarlimiter HBAR Limiter Acceptance Tests', function () {
...
+        expect(remainingHbarsBefore).to.be.gt(0);
+        const operatorBalanceBefore = (await mirrorNode.get(`/accounts/${operatorAccount}`, requestId)).balance.balance;
+
+        const largeContract = await Utils.deployContract(
+          largeContractJson.abi,
+          largeContractJson.bytecode,
+          accounts[0].wallet,
+        );
+        await largeContract.waitForDeployment();
+        expect(largeContract.target).to.not.be.null;
```
Comment (victor-yanev) [inline packages/server/tests/acceptance/hbarLimiter.spec.ts:186]: We can reuse the method `deployContract` inside `hbarLimiter.spec.ts` which already does the same checks:
```suggestion
        const largeContract = await deployContract(largeContractJson, accounts[0].wallet);
```

File: packages/server/tests/acceptance/hbarLimiter.spec.ts [hunk 6]
```diff
@@ -158,10 +164,69 @@ describe('@hbarlimiter HBAR Limiter Acceptance Tests', function () {
...
+          return total + sum;
+        }, 0);
+
+        const ethTxFee = sumAccountTransfers(ethereumTransaction.transfers, operatorAccount);
+        const totalOperatorFees = Math.abs(fileCreateFee + fileAppendFee + ethTxFee);
+        const remainingHbarsAfter = Number(await metrics.get(testConstants.METRICS.REMAINING_HBAR_LIMIT));
+        const hbarLimitReducedAmount = remainingHbarsBefore - remainingHbarsAfter;
+
+        expect(remainingHbarsAfter).to.be.lt(remainingHbarsBefore);
+        Assertions.expectWithinTolerance(hbarLimitReducedAmount, amountPaidByOperator, TOLERANCE);
```
Comment (victor-yanev) [inline packages/server/tests/acceptance/hbarLimiter.spec.ts:226]: **nit:** `expected` is the first argument in `expectWithinTolerance`
```suggestion
        Assertions.expectWithinTolerance(amountPaidByOperator, hbarLimitReducedAmount, TOLERANCE);
```

File: packages/relay/src/formatters.ts [hunk 7]
```diff
@@ -288,6 +288,16 @@ const isHex = (value: string): boolean => {
   return hexRegex.test(value);
 };
 
+// Returns the sum of all transfer amounts for the specified account. The amount is negative if the account is charged,
+// it is positive if the account is receiving it, thus the amount is first negated and then added to the sum.
+const getTransferAmountSumForAccount = (transactionRecord, accountId: undefined | string): number => {
```
Comment (victor-yanev) [inline packages/relay/src/formatters.ts:293]: It makes no sense to accept `undefined` values for `accountId` here:
```suggestion
const getTransferAmountSumForAccount = (transactionRecord, accountId: string): number => {
```

File: packages/relay/src/lib/clients/sdkClient.ts [hunk 8]
```diff
@@ -587,12 +587,7 @@ export class SDKClient {
       const transactionRecord: TransactionRecord = await transactionResponse.getRecord(this.clientMain);
 
       // get transactionFee and gasUsed for metrics
-      /**
-       * @todo: Determine how to separate the fee charged exclusively by the operator because
-       *        the transactionFee below includes the entire charges of the transaction,
-       *        with some portions paid by tx.from, not the operator.
-       */
-      transactionFee = transactionRecord.transactionFee.toTinybars().toNumber();
+      transactionFee = getTransferAmountSumForAccount(transactionRecord, this.clientMain.operatorAccountId?.toString());
```
Comment (victor-yanev) [inline packages/relay/src/lib/clients/sdkClient.ts:590]: Is it ever possible for `operatorAccountId` to be `null` or `undefined` here? 

If it's not possible, we can directly do:
```suggestion
      transactionFee = getTransferAmountSumForAccount(transactionRecord, this.clientMain.operatorAccountId!.toString());
```

File: packages/relay/src/lib/clients/sdkClient.ts [hunk 9]
```diff
@@ -603,7 +598,10 @@ export class SDKClient {
           .setNodeAccountIds([transactionResponse.nodeId])
           .setValidateReceiptStatus(false)
           .execute(this.clientMain);
-        transactionFee = transactionRecord.transactionFee.toTinybars().toNumber();
+        transactionFee = getTransferAmountSumForAccount(
+          transactionRecord,
+          this.clientMain.operatorAccountId?.toString(),
```
Comment (victor-yanev) [inline packages/relay/src/lib/clients/sdkClient.ts:603]: Same here:
```suggestion
          this.clientMain.operatorAccountId!.toString(),
```

**Review by victor-yanev — CHANGES_REQUESTED** [review]
LG, I've left a few suggestions

File: packages/relay/src/formatters.ts [hunk 10]
```diff
@@ -288,6 +288,16 @@ const isHex = (value: string): boolean => {
...
+// Returns the sum of all transfer amounts for the specified account. The amount is negative if the account is charged,
+// it is positive if the account is receiving it, thus the amount is first negated and then added to the sum.
+const getTransferAmountSumForAccount = (transactionRecord, accountId: string): number => {
+  return transactionRecord.transfers
+    .filter((transfer) => transfer.accountId.toString() === accountId)
+    .reduce((acc, transfer) => {
+      return BN.sum(acc, transfer.amount.toTinybars().negate()).toNumber();
+    }, 0);
+};
+
```
Comment (ebadiere) [inline packages/relay/src/formatters.ts:300]: Nit:
Have you considered something like the following for type safety?
```
const getTransferAmountSumForAccount = (transactionRecord, accountId: string): number => {
  return transactionRecord.transfers
    .filter((transfer) => transfer.accountId.toString() === accountId)
    .reduce((acc: BN, transfer) => {
      const negatedAmount = transfer.amount.toTinybars().negate();
      if (!(negatedAmount instanceof BN)) {
        throw new Error('Unexpected type: negatedAmount is not a BN instance');
      }
      return BN.sum(acc, negatedAmount).toNumber();
    }, 0);
};
```

**Review by ebadiere — COMMENTED** [review]
LG.  One question.

File: packages/server/tests/acceptance/hbarLimiter.spec.ts (hunk 3 above)
Comment (Ivo-Yankov) [reply packages/server/tests/acceptance/hbarLimiter.spec.ts]: This timeout was added to help isolate the metric results from the other tests. I moved this to `beforeAll` for this test suite. Basically it should reduce test flakiness

File: packages/server/tests/acceptance/hbarLimiter.spec.ts (hunk 2 above)
Comment (Ivo-Yankov) [reply packages/server/tests/acceptance/hbarLimiter.spec.ts]: I've noticed that the actual variance is currently around 0.01, but sometimes it is even greater. I set it to 0.02 to reduce flakiness, but as we make further improvements we should be able to safely reduce it to 0.001 or even 0.

**Review by victor-yanev — DISMISSED** [review]
LGTM

File: packages/server/tests/acceptance/hbarLimiter.spec.ts [hunk 11]
```diff
@@ -49,12 +51,75 @@ describe('@hbarlimiter HBAR Limiter Acceptance Tests', function () {
     };
 
     const verifyRemainingLimit = (expectedCost: number, remainingHbarsBefore: number, remainingHbarsAfter: number) => {
-      const delta = 0.001 * expectedCost; // 0.1% tolerance
-      global.logger.trace(`Expected cost: ${expectedCost} ±${delta}`);
-      global.logger.trace(`Actual cost: ${remainingHbarsBefore - remainingHbarsAfter}`);
+      const delta = 0.02 * expectedCost; // 0.1% tolerance
```
Comment (quiet-node) [inline packages/server/tests/acceptance/hbarLimiter.spec.ts:54]: nit: update comment

**Review by quiet-node — APPROVED** [review]
Great work! LGTM!

**Review by quiet-node — DISMISSED** [review]

**Review by victor-yanev — APPROVED** [review]

**Review by acuarica — DISMISSED** [review]
lg

**Review by ebadiere — APPROVED** [review]
