### PR TITLE
fix: trimmed preceding zeros for gas value (#2174)

### LINKED ISSUE #2174: Leading zeros for hex causes incompatibility with common utility packages
### Problem

The JSON RPC responses sometimes return gas values in Hex with leading zeros making it hard to use common utility packages such as https://pkg.go.dev/github.com/ethereum/go-ethereum/common/hexutil 
For example response from `eth_estimateGas` method

```
{
    "result": "0x0000000000006050",
    "jsonrpc": "2.0",
    "id": 1
}
```

### Solution

- Trim the leading zeros

### Alternatives

_No response_

### PR DESCRIPTION
**Pull request by quiet-node**
**Description**:
- added a quick helper method to convert the long zero gas value to a decimal value and revert it back to a hexadecimal value. This ensures that the gas value remains intact during the trimming process.
- fixed corresponded unit test

**Related issue(s)**:

Fixes #2174

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

### CODE REVIEW

File: packages/relay/src/formatters.ts [hunk 1]
```diff
@@ -181,6 +181,10 @@ const prepend0x = (input: string): string => {
   return input.startsWith(EMPTY_HEX) ? input : EMPTY_HEX + input;
 };
 
+const trimPrecedingZeros = (input: string) => {
```
Comment (Nana-EC) [inline packages/relay/src/formatters.ts:184]: Add tests for this method.
You should consider multiple inputs valid and invalid

**Review by Nana-EC — CHANGES_REQUESTED** [review]
Missing UTs

File: packages/relay/src/lib/eth.ts [hunk 2]
```diff
@@ -573,8 +574,9 @@ export class EthImpl implements Eth {
         },
         requestIdPrefix,
       );
-      if (contractCallResponse?.result) {
-        gas = prepend0x(contractCallResponse.result);
+
+      if (contractCallResponse && contractCallResponse.result) {
```
Comment (acuarica) [inline packages/relay/src/lib/eth.ts:578]: Out of curiosity, how does the old condition differ from this one?

**Review by acuarica — APPROVED** [review]
lg

File: packages/relay/src/formatters.ts (hunk 1 above)
Comment (quiet-node) [reply packages/relay/src/formatters.ts:184]: Pushed in the UTs!

File: packages/relay/src/lib/eth.ts (hunk 2 above)
Comment (quiet-node) [reply packages/relay/src/lib/eth.ts:578]: Ah yeah so the "?." operator allows for accessing properties of an object that maybe null or undefined without causing error. On the other hand, the `&&` condition firstly checks if contractCallResponse exists or not, and then access the result property. If contractCallResponse is null or undefined it will not attempt to access to the result property. Huh now that it's broken down it seems like they both eventually serve the same purpose in this context.

File: packages/relay/tests/lib/formatters.spec.ts [hunk 3]
```diff
@@ -262,6 +263,19 @@ describe('Formatters', () => {
...
   });
 
+  describe('trimPrecedingZeros', () => {
+    it('should trim all the unnecessary preceding 0s in a hex value', () => {
+      expect('0x' + trimPrecedingZeros('0x00000000603')).to.eq('0x603');
+      expect('0x' + trimPrecedingZeros('0x00000300042')).to.eq('0x300042');
+      expect('0x' + trimPrecedingZeros('0x00012000000')).to.eq('0x12000000');
+    });
+
+    it('should return NaN if inputs are invalid number', () => {
```
[the remark this answers is not in the document]
Comment (quiet-node) [reply packages/relay/tests/lib/formatters.spec.ts:277]: I added a case for `''`. This function accepts only a param of type string, so `null` and `undefined` would not be applicable.

**Review by AlfredoG87 — DISMISSED** [review]
LGTM 👍

**Review by Nana-EC — APPROVED** [review]

**Review by AlfredoG87 — APPROVED** [review]
