### PR TITLE
Fix `eth_getBalance` returning wrong balance

### LINKED ISSUE #992: `eth_getBalance` is wrong in rare cases
### Description

In some cases when fetching balance of account using ethers, we are receiving wrong one.

### Steps to reproduce

1. Get one of the already created accounts with local-node
2. Fetch balance
3. Send some amount to this account
4. Compare new balance with old, which should be old+amount.

### Additional context

_No response_

### Hedera network

other

### Version

latest

### Operating system

None

### PR DESCRIPTION
**Pull request by georgi-l95**
**Description**:
There is a bug with `eth_getBalance` returning wrong balances. This happens because the number or BigNumber that's being calculated exceeds `MAX_SAFE_INTEGER` and calculation comes out wrong. We need to use data type that allows to do some basic calculation without exceeding `MAX_SAFE_INTEGER`, BigInt allows that.

**Related issue(s)**:

Fixes #992 

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

### CODE REVIEW

File: packages/relay/src/lib/eth.ts [hunk 1]
```diff
@@ -665,15 +665,15 @@ export class EthImpl implements Eth {
                 }
 
                 balanceFound = true;
-                weibars = (currentBalance - balanceFromTxs) * constants.TINYBAR_TO_WEIBAR_COEF;
+                weibars = BigInt(currentBalance - balanceFromTxs) * BigInt(constants.TINYBAR_TO_WEIBAR_COEF);
```
Comment (Nana-EC) [inline packages/relay/src/lib/eth.ts:668]: Q: If a lot of these numbers were just BigInt by type definition would we need all the casting?
Or is this an optimization of sort?

**Review by Nana-EC — COMMENTED** [review]
Looking good. Casting and type question

File: packages/relay/src/lib/eth.ts (hunk 1 above)
Comment (georgi-l95) [reply packages/relay/src/lib/eth.ts:668]: No optimization in mind. I haven't defined them as BigInt, because in some other places where we are using those variables and constants, they are needed as numbers and that means converting them back to number. Problem is that when we multiply them by the weibar coefficient, we are losing the precision, when they are numbers or bignumbers. I've cached this coefficient as bigInt at the beginning of the tests to avoid casting, but for the other numbers I can't avoid the casting either from BigInt to number or the other way around.

**Review by Nana-EC — APPROVED** [review]

**Review by natanasow — APPROVED** [review]
LGTM
