### PR TITLE
fix: `eth_getBlockByHash` is using invalid cache record

### LINKED ISSUE #3250: `getBlockByHash` in the `eth_getTransactionReceipt` flow is using the wrong cache keys
### Description

We are getting alerts on intermittent `eth_getTransactionReceipt` calls with a 500 response.  Tracing through the logs we can see that the `getBlockByHash` call is missing a valid hash, right after the call to the mirror node on the `contracts/results` ebndpoint.  

### Steps to reproduce

1. Look through the logs for an `eth_getTransactionReceipt` call with a 500 response.
2. Note the request ID and trace through the logs the path of the request.
3. Notice the call to `getBlockByHash` is missing a valid hash.

```
[34mDEBUG[39m (rpc-server/84 on mainnet-hashio-85fd789b7-twzsv): [36m[Request ID: 51841ec6-3dc9-4dad-af6a-07c4c3f01e02] Validating method parameters for eth_getTransactionReceipt, params: ["0x411f2d52652ad237296f85041e382194d3fd5a7fb006e269975dede4652b70fc"][39m"
timestamp: "2024-11-11T15:30:19.138608570Z"

[36m[Request ID: 51841ec6-3dc9-4dad-af6a-07c4c3f01e02] getTransactionReceipt(0x411f2d52652ad237296f85041e382194d3fd5a7fb006e269975dede4652b70fc)

[36m[Request ID: 51841ec6-3dc9-4dad-af6a-07c4c3f01e02] [GET] contracts/results/0x411f2d52652ad237296f85041e382194d3fd5a7fb006e269975dede4652b70fc 200 4 ms

[36m[Request ID: 51841ec6-3dc9-4dad-af6a-07c4c3f01e02] [GET] contracts/results/0x411f2d52652ad237296f85041e382194d3fd5a7fb006e269975dede4652b70fc 200 2 ms

[36m[Request ID: 51841ec6-3dc9-4dad-af6a-07c4c3f01e02] getBlockByHash(hash=0x, showDetails=false)

[36m[Request ID: 51841ec6-3dc9-4dad-af6a-07c4c3f01e02] [GET] blocks/NaN 400 status

[36m[Request ID: 51841ec6-3dc9-4dad-af6a-07c4c3f01e02] Failed to retrieve block for hash 0x

[36m[Request ID: 51841ec6-3dc9-4dad-af6a-07c4c3f01e02] Error invoking RPC: Invalid parameter: hashOrNumber

[36m[Request ID: 51841ec6-3dc9-4dad-af6a-07c4c3f01e02] [POST]: eth_getTransactionReceipt 500 20 ms
```

### Additional context

_No response_

### Hedera network

mainnet

### Version

v0.59.3

### Operating system

Linux

### PR DESCRIPTION
**Pull request by natanasow**
**Description**:

We are getting alerts on intermittent `eth_getTransactionReceipt` calls with a 500 response.  Tracing through the logs we can see that the `getBlockByHash` call is missing a valid hash, right after the call to the mirror node on the `contracts/results` endpoint.  

**Steps to reproduce**:

1. Look through the logs for an `eth_getTransactionReceipt` call with a 500 response.
2. Note the request ID and trace through the logs the path of the request.
3. Notice the call to `getBlockByHash` is missing a valid hash.

```
[34mDEBUG[39m (rpc-server/84 on mainnet-hashio-85fd789b7-twzsv): [36m[Request ID: 51841ec6-3dc9-4dad-af6a-07c4c3f01e02] Validating method parameters for eth_getTransactionReceipt, params: ["0x411f2d52652ad237296f85041e382194d3fd5a7fb006e269975dede4652b70fc"][39m"
timestamp: "2024-11-11T15:30:19.138608570Z"

[36m[Request ID: 51841ec6-3dc9-4dad-af6a-07c4c3f01e02] getTransactionReceipt(0x411f2d52652ad237296f85041e382194d3fd5a7fb006e269975dede4652b70fc)

[36m[Request ID: 51841ec6-3dc9-4dad-af6a-07c4c3f01e02] [GET] contracts/results/0x411f2d52652ad237296f85041e382194d3fd5a7fb006e269975dede4652b70fc 200 4 ms

[36m[Request ID: 51841ec6-3dc9-4dad-af6a-07c4c3f01e02] [GET] contracts/results/0x411f2d52652ad237296f85041e382194d3fd5a7fb006e269975dede4652b70fc 200 2 ms

[36m[Request ID: 51841ec6-3dc9-4dad-af6a-07c4c3f01e02] getBlockByHash(hash=0x, showDetails=false)

[36m[Request ID: 51841ec6-3dc9-4dad-af6a-07c4c3f01e02] [GET] blocks/NaN 400 status

[36m[Request ID: 51841ec6-3dc9-4dad-af6a-07c4c3f01e02] Failed to retrieve block for hash 0x

[36m[Request ID: 51841ec6-3dc9-4dad-af6a-07c4c3f01e02] Error invoking RPC: Invalid parameter: hashOrNumber

[36m[Request ID: 51841ec6-3dc9-4dad-af6a-07c4c3f01e02] [POST]: eth_getTransactionReceipt 500 20 ms
```

**Related issue(s)**:

Fixes #3250

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

### CODE REVIEW

File: packages/relay/src/lib/clients/mirrorNodeClient.ts [hunk 1]
```diff
@@ -749,14 +751,21 @@ export class MirrorNodeClient {
...
     const contractResult = await this.getContractResult(transactionIdOrHash, requestDetails);
-    if (contractResult && !(contractResult.transaction_index && contractResult.block_number)) {
+    if (
+      contractResult &&
+      !(
+        contractResult.transaction_index &&
+        contractResult.block_number &&
+        contractResult.block_hash != EthImpl.emptyHex
+      )
+    ) {
```
Comment (ebadiere) [inline packages/relay/src/lib/clients/mirrorNodeClient.ts:768]: Nit.  For readability perhaps:
```
if (
  contractResult &&
  (
    !contractResult.transaction_index ||
    !contractResult.block_number ||
    contractResult.block_hash === EthImpl.emptyHex
  )
) {...
```

**Review by ebadiere — APPROVED** [review]
LG.

**Review by nadezhdapopovaa — APPROVED** [review]
