### PR TITLE
fix: added logging to HBARLimit class

### LINKED ISSUE #2736: The logging in the HbarLimit class does not reference the requestId.
### Problem

The logging in the HbarLimit class does not reference the requestId, making it difficult to associate each log with its corresponding request.

### Solution

Add requestId to logging in HbarClass

### Alternatives

_No response_

### PR DESCRIPTION
**Pull request by quiet-node**
**Description**: 
This small PR added more logs to HBARLimit class

**Related issue(s)**:

Fixes #2736

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

### CODE REVIEW

File: packages/relay/src/lib/hbarlimiter/index.ts [hunk 1]
```diff
@@ -43,10 +44,10 @@ export default class HbarLimit {
       this.duration = duration;
     }
     this.remainingBudget = this.total;
-    this.logger.trace(`this.remainingBudget: ${this.remainingBudget}`);
-
     this.reset = currentDateNow + this.duration;
 
+    this.logger.trace(`remainingBudget=${this.remainingBudget} tℏ, resetTimeStamp=${this.reset}`);
```
Comment (acuarica) [inline packages/relay/src/lib/hbarlimiter/index.ts:49]: Inconsistent case for `resetTimeStamp` here and in the other log traces.

**Review by acuarica — APPROVED** [review]
lg, left small nit

**Review by ebadiere — APPROVED** [review]
LG.
