### PR TITLE
eth_feeHistory wrongly returns error

### LINKED ISSUE #813: eth_feeHistory wrongly returns error Incorrect block
### Description

Occasionally when making `eth_feeHistory` calls the relay returns the error **Incorrect block** such as in the following error response:
```
{
   "reason":"bad response",
   "code":"SERVER_ERROR",
   "status":400,
   "headers":{
      "date":"Wed, 11 Jan 2023 10:29:29 GMT",
      "content-type":"application/json; charset=utf-8",
      "content-length":"200",
      "connection":"close",
      "access-control-allow-origin":"*",
      "access-control-allow-methods":"GET,HEAD,PUT,POST,DELETE",
      "via":"1.1 google",
      "cf-cache-status":"DYNAMIC",
      "server":"cloudflare",
      "cf-ray":"787cf878ecf68023-IAD"
   },
   "body":{
      "jsonrpc":"2.0",
      "id":3799,
      "error":{
         "code":-32000,
         "name":"Incorrect block",
         "message":"[Request ID: 2c192c09-7422-4204-a87e-665b2e09ba79] Request beyond head block: requested 29328315, head 29328309"
      }
   },
   "requestBody":{
      "method":"eth_feeHistory",
      "params":[
         "0x4",
         "latest",
         [
            50
         ]
      ],
      "id":3799,
      "jsonrpc":"2.0"
   },
   "requestMethod":"POST",
   "url":"https://testnet.hashio.io/api"
}
```
The block isn't passed explicitly in the `eth_feeHistory` request rather `latest` is as indicated above. Additionally, the error response doesn't add up as at the time of the request i.e. 11 Jan 2023 10:29:29 GMT [Block 29328315](https://hashscan.io/testnet/block/29328315) had already been created and the head block was definitely NOT the earlier block 29328309 as the error message states.

### Steps to reproduce

As stated the error happens occasionally, but I think the above explanation is sufficient evidence of the issue.

### Additional context

_No response_

### Hedera network

testnet

### Version

hashio-relay/0.15.0

### Operating system

None

### PR DESCRIPTION
**Pull request by natanasow**
Signed-off-by: nikolay <n.atanasow94@gmail.com>

**Description**:

**Related issue(s)**:

Fixes #813

**Notes for reviewer**:

**Checklist**

- [x] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

### CODE REVIEW

**Review by georgi-l95 — APPROVED** [review]
LG

File: packages/relay/src/lib/eth.ts [hunk 1]
```diff
@@ -172,7 +172,9 @@ export class EthImpl implements Eth {
 
     try {
       const latestBlockNumber = await this.translateBlockTag(EthImpl.blockLatest, requestId);
-      const newestBlockNumber = await this.translateBlockTag(newestBlock, requestId);
+      const newestBlockNumber = (newestBlock == EthImpl.blockLatest || newestBlock == EthImpl.blockPending)
```
Comment (Nana-EC) [inline packages/relay/src/lib/eth.ts:175]: Please add a test that ensure the previous case does not occur.
That is a test based on the logic that
- if `newestBlock == EthImpl.blockLatest` then `newestBlockNumber` = `latestBlockNumber`
- if `newestBlock == EthImpl.blockPending` then `newestBlockNumber` = `this.translateBlockTag(newestBlock, requestId)`

**Review by Nana-EC — CHANGES_REQUESTED** [review]
missing tests

File: packages/relay/src/lib/eth.ts (hunk 1 above)
Comment (AlfredoG87) [reply packages/relay/src/lib/eth.ts:175]: > if newestBlock == EthImpl.blockPending then newestBlockNumber =

Should not be also = `latestBlockNumber` or do you mean that this case should not happen?

**Comment by AlfredoG87** [comment]
Noticed that Acceptance Tests check failed due to 1 error on API Job with error:

 

> 1) RPC Server Acceptance Tests
       Acceptance tests
         @api RPC Server Acceptance Tests
           RPC Server Acceptance Tests
             eth_getBalance
               @release should correctly execute "eth_getBalance" with block number in the last 15 minutes with several txs around that time:

      AssertionError: expected '2999479740000000000' to equal '2999479750000000000'
      + expected - actual

      -2999479740000000000
      +2999479750000000000
      
      at Context.<anonymous> (packages/server/tests/acceptance/rpc.spec.ts:1041:73)


is this difference expected?

File: packages/relay/src/lib/eth.ts (hunk 1 above)
Comment (ebadiere) [reply packages/relay/src/lib/eth.ts:175]: Good question, since a call to translateBlockTag with a block in a pending state should also return the latest block.

Comment (ebadiere) [reply packages/relay/src/lib/eth.ts:175]: Good question since the call to translateBlockTag with a newestBlock in a pending state will return the "most recent block number" by calling  the getLatestBlock on the mirrorNodeClient.  The tests seem return the same result when passed "latest" or "pending".

**Comment by georgi-l95** [comment]
> 



> Noticed that Acceptance Tests check failed due to 1 error on API Job with error:
> 
> > 1. RPC Server Acceptance Tests
> >    Acceptance tests
> >    @api RPC Server Acceptance Tests
> >    RPC Server Acceptance Tests
> >    eth_getBalance
> >    @Release should correctly execute "eth_getBalance" with block number in the last 15 minutes with several txs around that time:
> 
> ```
>   AssertionError: expected '2999479740000000000' to equal '2999479750000000000'
>   + expected - actual
> 
>   -2999479740000000000
>   +2999479750000000000
>   
>   at Context.<anonymous> (packages/server/tests/acceptance/rpc.spec.ts:1041:73)
> ```
> 
> is this difference expected?

No, but because we are doing several transactions and fetching with multiple requests, even if one fails, the whole scenario fails. So it's bound to happen sometime. It won't be a bad idea to try and fix this, but it won't be that easy.

**Comment by AlfredoG87** [comment]
> > 
> 
> > Noticed that Acceptance Tests check failed due to 1 error on API Job with error:
> > > 1. RPC Server Acceptance Tests
> > >    Acceptance tests
> > >    @api RPC Server Acceptance Tests
> > >    RPC Server Acceptance Tests
> > >    eth_getBalance
> > >    @Release should correctly execute "eth_getBalance" with block number in the last 15 minutes with several txs around that time:
> > 
> > 
> > ```
> >   AssertionError: expected '2999479740000000000' to equal '2999479750000000000'
> >   + expected - actual
> > 
> >   -2999479740000000000
> >   +2999479750000000000
> >   
> >   at Context.<anonymous> (packages/server/tests/acceptance/rpc.spec.ts:1041:73)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > is this difference expected?
> 
> No, but because we are doing several transactions and fetching with multiple requests, even if one fails, the whole scenario fails. So it's bound to happen sometime. It won't be a bad idea to try and fix this, but it won't be that easy.

I just ran the test again and this time it completed without issues, thanks!!

**Review by Nana-EC — APPROVED** [review]
