### PR TITLE
Fix latency metric capture logic

### LINKED ISSUE #176: Metrics for latency of calls should not be counter label
### Description

The metrics for the latency of request calls is currently captured as a counter label.
This is incorrect as latency ms values often differ.

### Steps to reproduce

1. Run the relay
2. Check `/metrics`

### Additional context

_No response_

### Hedera network

other

### Version

v0.2.0-SNAPSHOT

### Operating system

_No response_

### PR DESCRIPTION
**Pull request by Nana-EC**
Signed-off-by: Nana-EC <nana@swirldslabs.com>

**Description**:
Capture latency correctly in prom-client

- remove latency from counter
- add latency to histogram

**Related issue(s)**:

Fixes #176 

**Notes for reviewer**:
Tested against previewnet and wallet

Example output
```
# HELP rpc_relay_method_response_hist JSON RPC method status latency histogram
# TYPE rpc_relay_method_response_hist histogram
rpc_relay_method_response_hist_bucket{le="0.005",method="eth_blockNumber",status="200"} 0
rpc_relay_method_response_hist_bucket{le="0.01",method="eth_blockNumber",status="200"} 0
rpc_relay_method_response_hist_bucket{le="0.025",method="eth_blockNumber",status="200"} 0
rpc_relay_method_response_hist_bucket{le="0.05",method="eth_blockNumber",status="200"} 0
rpc_relay_method_response_hist_bucket{le="0.1",method="eth_blockNumber",status="200"} 0
rpc_relay_method_response_hist_bucket{le="0.25",method="eth_blockNumber",status="200"} 0
rpc_relay_method_response_hist_bucket{le="0.5",method="eth_blockNumber",status="200"} 0
rpc_relay_method_response_hist_bucket{le="1",method="eth_blockNumber",status="200"} 0
rpc_relay_method_response_hist_bucket{le="2.5",method="eth_blockNumber",status="200"} 0
rpc_relay_method_response_hist_bucket{le="5",method="eth_blockNumber",status="200"} 0
rpc_relay_method_response_hist_bucket{le="10",method="eth_blockNumber",status="200"} 0
rpc_relay_method_response_hist_bucket{le="+Inf",method="eth_blockNumber",status="200"} 8
rpc_relay_method_response_hist_sum{method="eth_blockNumber",status="200"} 3086
rpc_relay_method_response_hist_count{method="eth_blockNumber",status="200"} 8
rpc_relay_method_response_hist_bucket{le="0.005",method="eth_getBlockByNumber",status="200"} 0
rpc_relay_method_response_hist_bucket{le="0.01",method="eth_getBlockByNumber",status="200"} 0
rpc_relay_method_response_hist_bucket{le="0.025",method="eth_getBlockByNumber",status="200"} 0
rpc_relay_method_response_hist_bucket{le="0.05",method="eth_getBlockByNumber",status="200"} 0
rpc_relay_method_response_hist_bucket{le="0.1",method="eth_getBlockByNumber",status="200"} 0
rpc_relay_method_response_hist_bucket{le="0.25",method="eth_getBlockByNumber",status="200"} 0
rpc_relay_method_response_hist_bucket{le="0.5",method="eth_getBlockByNumber",status="200"} 0
rpc_relay_method_response_hist_bucket{le="1",method="eth_getBlockByNumber",status="200"} 0
rpc_relay_method_response_hist_bucket{le="2.5",method="eth_getBlockByNumber",status="200"} 0
rpc_relay_method_response_hist_bucket{le="5",method="eth_getBlockByNumber",status="200"} 0
rpc_relay_method_response_hist_bucket{le="10",method="eth_getBlockByNumber",status="200"} 0
rpc_relay_method_response_hist_bucket{le="+Inf",method="eth_getBlockByNumber",status="200"} 6
rpc_relay_method_response_hist_sum{method="eth_getBlockByNumber",status="200"} 1656
rpc_relay_method_response_hist_count{method="eth_getBlockByNumber",status="200"} 6
rpc_relay_method_response_hist_bucket{le="0.005",method="eth_getBalance",status="200"} 0
rpc_relay_method_response_hist_bucket{le="0.01",method="eth_getBalance",status="200"} 0
rpc_relay_method_response_hist_bucket{le="0.025",method="eth_getBalance",status="200"} 0
rpc_relay_method_response_hist_bucket{le="0.05",method="eth_getBalance",status="200"} 0
rpc_relay_method_response_hist_bucket{le="0.1",method="eth_getBalance",status="200"} 0
rpc_relay_method_response_hist_bucket{le="0.25",method="eth_getBalance",status="200"} 0
rpc_relay_method_response_hist_bucket{le="0.5",method="eth_getBalance",status="200"} 0
rpc_relay_method_response_hist_bucket{le="1",method="eth_getBalance",status="200"} 0
rpc_relay_method_response_hist_bucket{le="2.5",method="eth_getBalance",status="200"} 0
rpc_relay_method_response_hist_bucket{le="5",method="eth_getBalance",status="200"} 0
rpc_relay_method_response_hist_bucket{le="10",method="eth_getBalance",status="200"} 0
rpc_relay_method_response_hist_bucket{le="+Inf",method="eth_getBalance",status="200"} 44
rpc_relay_method_response_hist_sum{method="eth_getBalance",status="200"} 2084
rpc_relay_method_response_hist_count{method="eth_getBalance",status="200"} 44
rpc_relay_method_response_hist_bucket{le="0.005",method="eth_feeHistory",status="200"} 0
rpc_relay_method_response_hist_bucket{le="0.01",method="eth_feeHistory",status="200"} 0
rpc_relay_method_response_hist_bucket{le="0.025",method="eth_feeHistory",status="200"} 0
rpc_relay_method_response_hist_bucket{le="0.05",method="eth_feeHistory",status="200"} 0
rpc_relay_method_response_hist_bucket{le="0.1",method="eth_feeHistory",status="200"} 0
rpc_relay_method_response_hist_bucket{le="0.25",method="eth_feeHistory",status="200"} 0
rpc_relay_method_response_hist_bucket{le="0.5",method="eth_feeHistory",status="200"} 0
rpc_relay_method_response_hist_bucket{le="1",method="eth_feeHistory",status="200"} 0
rpc_relay_method_response_hist_bucket{le="2.5",method="eth_feeHistory",status="200"} 0
rpc_relay_method_response_hist_bucket{le="5",method="eth_feeHistory",status="200"} 0
rpc_relay_method_response_hist_bucket{le="10",method="eth_feeHistory",status="200"} 0
rpc_relay_method_response_hist_bucket{le="+Inf",method="eth_feeHistory",status="200"} 18
rpc_relay_method_response_hist_sum{method="eth_feeHistory",status="200"} 8887
rpc_relay_method_response_hist_count{method="eth_feeHistory",status="200"} 18
rpc_relay_method_response_hist_bucket{le="0.005",method="eth_gasPrice",status="200"} 3
rpc_relay_method_response_hist_bucket{le="0.01",method="eth_gasPrice",status="200"} 3
rpc_relay_method_response_hist_bucket{le="0.025",method="eth_gasPrice",status="200"} 3
rpc_relay_method_response_hist_bucket{le="0.05",method="eth_gasPrice",status="200"} 3
rpc_relay_method_response_hist_bucket{le="0.1",method="eth_gasPrice",status="200"} 3
rpc_relay_method_response_hist_bucket{le="0.25",method="eth_gasPrice",status="200"} 3
rpc_relay_method_response_hist_bucket{le="0.5",method="eth_gasPrice",status="200"} 3
rpc_relay_method_response_hist_bucket{le="1",method="eth_gasPrice",status="200"} 3
rpc_relay_method_response_hist_bucket{le="2.5",method="eth_gasPrice",status="200"} 3
rpc_relay_method_response_hist_bucket{le="5",method="eth_gasPrice",status="200"} 3
rpc_relay_method_response_hist_bucket{le="10",method="eth_gasPrice",status="200"} 3
rpc_relay_method_response_hist_bucket{le="+Inf",method="eth_gasPrice",status="200"} 4
rpc_relay_method_response_hist_sum{method="eth_gasPrice",status="200"} 375
rpc_relay_method_response_hist_count{method="eth_gasPrice",status="200"} 4
rpc_relay_method_response_hist_bucket{le="0.005",method="eth_call",status="200"} 0
rpc_relay_method_response_hist_bucket{le="0.01",method="eth_call",status="200"} 0
rpc_relay_method_response_hist_bucket{le="0.025",method="eth_call",status="200"} 0
rpc_relay_method_response_hist_bucket{le="0.05",method="eth_call",status="200"} 0
rpc_relay_method_response_hist_bucket{le="0.1",method="eth_call",status="200"} 0
rpc_relay_method_response_hist_bucket{le="0.25",method="eth_call",status="200"} 0
rpc_relay_method_response_hist_bucket{le="0.5",method="eth_call",status="200"} 0
rpc_relay_method_response_hist_bucket{le="1",method="eth_call",status="200"} 0
rpc_relay_method_response_hist_bucket{le="2.5",method="eth_call",status="200"} 0
rpc_relay_method_response_hist_bucket{le="5",method="eth_call",status="200"} 0
rpc_relay_method_response_hist_bucket{le="10",method="eth_call",status="200"} 0
rpc_relay_method_response_hist_bucket{le="+Inf",method="eth_call",status="200"} 8
rpc_relay_method_response_hist_sum{method="eth_call",status="200"} 732
rpc_relay_method_response_hist_count{method="eth_call",status="200"} 8
rpc_relay_method_response_hist_bucket{le="0.005",method="eth_call",status="-32603"} 0
rpc_relay_method_response_hist_bucket{le="0.01",method="eth_call",status="-32603"} 0
rpc_relay_method_response_hist_bucket{le="0.025",method="eth_call",status="-32603"} 0
rpc_relay_method_response_hist_bucket{le="0.05",method="eth_call",status="-32603"} 0
rpc_relay_method_response_hist_bucket{le="0.1",method="eth_call",status="-32603"} 0
rpc_relay_method_response_hist_bucket{le="0.25",method="eth_call",status="-32603"} 0
rpc_relay_method_response_hist_bucket{le="0.5",method="eth_call",status="-32603"} 0
rpc_relay_method_response_hist_bucket{le="1",method="eth_call",status="-32603"} 0
rpc_relay_method_response_hist_bucket{le="2.5",method="eth_call",status="-32603"} 0
rpc_relay_method_response_hist_bucket{le="5",method="eth_call",status="-32603"} 0
rpc_relay_method_response_hist_bucket{le="10",method="eth_call",status="-32603"} 0
rpc_relay_method_response_hist_bucket{le="+Inf",method="eth_call",status="-32603"} 15
rpc_relay_method_response_hist_sum{method="eth_call",status="-32603"} 1262
rpc_relay_method_response_hist_count{method="eth_call",status="-32603"} 15
rpc_relay_method_response_hist_bucket{le="0.005",method="eth_estimateGas",status="200"} 4
rpc_relay_method_response_hist_bucket{le="0.01",method="eth_estimateGas",status="200"} 4
rpc_relay_method_response_hist_bucket{le="0.025",method="eth_estimateGas",status="200"} 4
rpc_relay_method_response_hist_bucket{le="0.05",method="eth_estimateGas",status="200"} 4
rpc_relay_method_response_hist_bucket{le="0.1",method="eth_estimateGas",status="200"} 4
rpc_relay_method_response_hist_bucket{le="0.25",method="eth_estimateGas",status="200"} 4
rpc_relay_method_response_hist_bucket{le="0.5",method="eth_estimateGas",status="200"} 4
rpc_relay_method_response_hist_bucket{le="1",method="eth_estimateGas",status="200"} 4
rpc_relay_method_response_hist_bucket{le="2.5",method="eth_estimateGas",status="200"} 4
rpc_relay_method_response_hist_bucket{le="5",method="eth_estimateGas",status="200"} 4
rpc_relay_method_response_hist_bucket{le="10",method="eth_estimateGas",status="200"} 4
rpc_relay_method_response_hist_bucket{le="+Inf",method="eth_estimateGas",status="200"} 4
rpc_relay_method_response_hist_sum{method="eth_estimateGas",status="200"} 0
rpc_relay_method_response_hist_count{method="eth_estimateGas",status="200"} 4
rpc_relay_method_response_hist_bucket{le="0.005",method="eth_getTransactionCount",status="200"} 0
rpc_relay_method_response_hist_bucket{le="0.01",method="eth_getTransactionCount",status="200"} 0
rpc_relay_method_response_hist_bucket{le="0.025",method="eth_getTransactionCount",status="200"} 0
rpc_relay_method_response_hist_bucket{le="0.05",method="eth_getTransactionCount",status="200"} 0
rpc_relay_method_response_hist_bucket{le="0.1",method="eth_getTransactionCount",status="200"} 0
rpc_relay_method_response_hist_bucket{le="0.25",method="eth_getTransactionCount",status="200"} 0
rpc_relay_method_response_hist_bucket{le="0.5",method="eth_getTransactionCount",status="200"} 0
rpc_relay_method_response_hist_bucket{le="1",method="eth_getTransactionCount",status="200"} 0
rpc_relay_method_response_hist_bucket{le="2.5",method="eth_getTransactionCount",status="200"} 0
rpc_relay_method_response_hist_bucket{le="5",method="eth_getTransactionCount",status="200"} 0
rpc_relay_method_response_hist_bucket{le="10",method="eth_getTransactionCount",status="200"} 0
rpc_relay_method_response_hist_bucket{le="+Inf",method="eth_getTransactionCount",status="200"} 2
rpc_relay_method_response_hist_sum{method="eth_getTransactionCount",status="200"} 169
rpc_relay_method_response_hist_count{method="eth_getTransactionCount",status="200"} 2
rpc_relay_method_response_hist_bucket{le="0.005",method="eth_sendRawTransaction",status="200"} 0
rpc_relay_method_response_hist_bucket{le="0.01",method="eth_sendRawTransaction",status="200"} 0
rpc_relay_method_response_hist_bucket{le="0.025",method="eth_sendRawTransaction",status="200"} 0
rpc_relay_method_response_hist_bucket{le="0.05",method="eth_sendRawTransaction",status="200"} 0
rpc_relay_method_response_hist_bucket{le="0.1",method="eth_sendRawTransaction",status="200"} 0
rpc_relay_method_response_hist_bucket{le="0.25",method="eth_sendRawTransaction",status="200"} 0
rpc_relay_method_response_hist_bucket{le="0.5",method="eth_sendRawTransaction",status="200"} 0
rpc_relay_method_response_hist_bucket{le="1",method="eth_sendRawTransaction",status="200"} 0
rpc_relay_method_response_hist_bucket{le="2.5",method="eth_sendRawTransaction",status="200"} 0
rpc_relay_method_response_hist_bucket{le="5",method="eth_sendRawTransaction",status="200"} 0
rpc_relay_method_response_hist_bucket{le="10",method="eth_sendRawTransaction",status="200"} 0
rpc_relay_method_response_hist_bucket{le="+Inf",method="eth_sendRawTransaction",status="200"} 2
rpc_relay_method_response_hist_sum{method="eth_sendRawTransaction",status="200"} 6445
rpc_relay_method_response_hist_count{method="eth_sendRawTransaction",status="200"} 2
rpc_relay_method_response_hist_bucket{le="0.005",method="eth_getCode",status="200"} 0
rpc_relay_method_response_hist_bucket{le="0.01",method="eth_getCode",status="200"} 0
rpc_relay_method_response_hist_bucket{le="0.025",method="eth_getCode",status="200"} 0
rpc_relay_method_response_hist_bucket{le="0.05",method="eth_getCode",status="200"} 0
rpc_relay_method_response_hist_bucket{le="0.1",method="eth_getCode",status="200"} 0
rpc_relay_method_response_hist_bucket{le="0.25",method="eth_getCode",status="200"} 0
rpc_relay_method_response_hist_bucket{le="0.5",method="eth_getCode",status="200"} 0
rpc_relay_method_response_hist_bucket{le="1",method="eth_getCode",status="200"} 0
rpc_relay_method_response_hist_bucket{le="2.5",method="eth_getCode",status="200"} 0
rpc_relay_method_response_hist_bucket{le="5",method="eth_getCode",status="200"} 0
rpc_relay_method_response_hist_bucket{le="10",method="eth_getCode",status="200"} 0
rpc_relay_method_response_hist_bucket{le="+Inf",method="eth_getCode",status="200"} 1
rpc_relay_method_response_hist_sum{method="eth_getCode",status="200"} 52
rpc_relay_method_response_hist_count{method="eth_getCode",status="200"} 1
rpc_relay_method_response_hist_bucket{le="0.005",method="eth_getTransactionReceipt",status="200"} 0
rpc_relay_method_response_hist_bucket{le="0.01",method="eth_getTransactionReceipt",status="200"} 0
rpc_relay_method_response_hist_bucket{le="0.025",method="eth_getTransactionReceipt",status="200"} 0
rpc_relay_method_response_hist_bucket{le="0.05",method="eth_getTransactionReceipt",status="200"} 0
rpc_relay_method_response_hist_bucket{le="0.1",method="eth_getTransactionReceipt",status="200"} 0
rpc_relay_method_response_hist_bucket{le="0.25",method="eth_getTransactionReceipt",status="200"} 0
rpc_relay_method_response_hist_bucket{le="0.5",method="eth_getTransactionReceipt",status="200"} 0
rpc_relay_method_response_hist_bucket{le="1",method="eth_getTransactionReceipt",status="200"} 0
rpc_relay_method_response_hist_bucket{le="2.5",method="eth_getTransactionReceipt",status="200"} 0
rpc_relay_method_response_hist_bucket{le="5",method="eth_getTransactionReceipt",status="200"} 0
rpc_relay_method_response_hist_bucket{le="10",method="eth_getTransactionReceipt",status="200"} 0
rpc_relay_method_response_hist_bucket{le="+Inf",method="eth_getTransactionReceipt",status="200"} 2
rpc_relay_method_response_hist_sum{method="eth_getTransactionReceipt",status="200"} 445
rpc_relay_method_response_hist_count{method="eth_getTransactionReceipt",status="200"} 2
rpc_relay_method_response_hist_bucket{le="0.005",method="eth_getBlockByHash",status="200"} 0
rpc_relay_method_response_hist_bucket{le="0.01",method="eth_getBlockByHash",status="200"} 0
rpc_relay_method_response_hist_bucket{le="0.025",method="eth_getBlockByHash",status="200"} 0
rpc_relay_method_response_hist_bucket{le="0.05",method="eth_getBlockByHash",status="200"} 0
rpc_relay_method_response_hist_bucket{le="0.1",method="eth_getBlockByHash",status="200"} 0
rpc_relay_method_response_hist_bucket{le="0.25",method="eth_getBlockByHash",status="200"} 0
rpc_relay_method_response_hist_bucket{le="0.5",method="eth_getBlockByHash",status="200"} 0
rpc_relay_method_response_hist_bucket{le="1",method="eth_getBlockByHash",status="200"} 0
rpc_relay_method_response_hist_bucket{le="2.5",method="eth_getBlockByHash",status="200"} 0
rpc_relay_method_response_hist_bucket{le="5",method="eth_getBlockByHash",status="200"} 0
rpc_relay_method_response_hist_bucket{le="10",method="eth_getBlockByHash",status="200"} 0
rpc_relay_method_response_hist_bucket{le="+Inf",method="eth_getBlockByHash",status="200"} 2
rpc_relay_method_response_hist_sum{method="eth_getBlockByHash",status="200"} 965
rpc_relay_method_response_hist_count{method="eth_getBlockByHash",status="200"} 2
```

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

### CODE REVIEW

File: packages/server/src/server.ts [hunk 1]
```diff
@@ -43,12 +43,21 @@ const cors = require('koa-cors');
 const app = new Koa();
 const rpc = koaJsonRpc();
 
+const responseSuccessLabel = 'Success';
+const responseFailureLabel = 'Failure';
 const register = new Registry();
 collectDefaultMetrics({ register, prefix: 'rpc_relay_' });
 const methodSuccessLatencyCounter = new Counter({
```
Comment (shemnon) [inline packages/server/src/server.ts:50]: Just `methodSuccessCounter` since there is now `methodLatencyHistogram`?

**Review by shemnon — APPROVED** [review]

File: packages/server/src/server.ts [hunk 2]
```diff
@@ -118,14 +127,16 @@ const logAndHandleResponse = async (methodName, methodFunction) => {
   const messagePrefix = `[POST] ${methodName}:`;
   try {
     const response = await methodFunction();
-    const success = response instanceof JsonRpcError ? 'Failure' : 'Success';
+    const success = response instanceof JsonRpcError ? responseFailureLabel : responseSuccessLabel;
```
Comment (steven-sheehy) [inline packages/server/src/server.ts:130]: `success=Success` and `success=Failure` are repetitive and don't make sense or provide details. Instead suggest `statusCode=-32600` or `status=Invalid request|Success|...`.

File: packages/server/src/server.ts [hunk 3]
```diff
@@ -118,14 +127,16 @@ const logAndHandleResponse = async (methodName, methodFunction) => {
...
     ms = Date.now() - start;
-    methodSuccessLatencyCounter.inc({ method: methodName, success: success, latency: ms });
+    methodSuccessLatencyCounter.inc({ method: methodName, success: success });
+    methodLatencyHistogram.labels(methodName, success).observe(ms);
     logger.info(`${messagePrefix} ${ms} ms ${success}`);
     return response;
   } catch (e) {
     ms = Date.now() - start;
-    methodSuccessLatencyCounter.inc({ method: methodName, success: 'Failure', latency: ms });
+    methodSuccessLatencyCounter.inc({ method: methodName, success: responseFailureLabel });
```
Comment (steven-sheehy) [inline packages/server/src/server.ts:138]: Is this handling RPC errors like the error codes mentioned [here](https://deploy-preview-482--hedera-hips.netlify.app/hip/hip-482#errors)? Those should be considered as unsuccessful for metrics purposes.

File: packages/server/src/server.ts [hunk 4]
```diff
@@ -43,12 +43,21 @@ const cors = require('koa-cors');
...
 
+const responseSuccessLabel = 'Success';
+const responseFailureLabel = 'Failure';
 const register = new Registry();
 collectDefaultMetrics({ register, prefix: 'rpc_relay_' });
 const methodSuccessLatencyCounter = new Counter({
-  name: 'rpc_method_success_latency_counter',
-  help: 'JSON RPC method success latencycounter',
-  labelNames: ['method', 'success', 'latency'],
+  name: 'rpc_method_success_counter',
```
Comment (steven-sheehy) [inline packages/server/src/server.ts:51]: * Shouldn't name it as `success` counter since it tracks both success and non-success and it would be inefficient to have a separate non-success counter.
* Its customary to name counters as ending in `count`.
* Other metrics start with `rpc_relay` so this should too

Suggest `rpc_relay_request_count`

File: packages/server/src/server.ts (hunk 1 above)
Comment (steven-sheehy) [reply packages/server/src/server.ts:50]: A histogram should already include a timer along with it, so can probably just drop the counter. If that's not the case then the counter should be converted to a timer as counters for requests are not useful, IMO.

**Review by steven-sheehy — CHANGES_REQUESTED** [review]

File: packages/server/src/server.ts (hunk 3 above)
Comment (Nana-EC) [reply packages/server/src/server.ts:138]: Updated to capture code though

File: packages/server/src/server.ts (hunk 2 above)
Comment (Nana-EC) [reply packages/server/src/server.ts:130]: I had been thinking on this when pushing the PR out, was planning on addressing in a separate ticket.
Will capture the status code though

File: packages/server/src/server.ts (hunk 1 above)
Comment (Nana-EC) [reply packages/server/src/server.ts]: Took both your suggestions and simplified

File: packages/server/src/server.ts (hunk 2 above)
Comment (Nana-EC) [reply packages/server/src/server.ts]: Updated

File: packages/server/src/server.ts [hunk 5]
```diff
@@ -43,12 +43,15 @@ const cors = require('koa-cors');
...
+const responseInternalErrorCode = '-32603';
 const register = new Registry();
 collectDefaultMetrics({ register, prefix: 'rpc_relay_' });
-const methodSuccessLatencyCounter = new Counter({
-  name: 'rpc_method_success_latency_counter',
-  help: 'JSON RPC method success latencycounter',
-  labelNames: ['method', 'success', 'latency'],
+
+const methodResponseHistogram = new Histogram({
+  name: 'rpc_relay_method_response_histogram',
```
[the remark this answers is not in the document]
Comment (Nana-EC) [reply packages/server/src/server.ts]: Updated

**Review by steven-sheehy — APPROVED** [review]
