### PR TITLE
fix: let 0 value transactions pass

### LINKED ISSUE #3105: Let 0-value Ethereum transactions pass
### Problem

Currently, the JSON-RPC relay forces the Ethereum transaction value to be greater than 0 in order to be accepted. 

This isn't a real network constraint, both Hedera and Ethereum accept 0-value transactions, but it is enforced in two parts of the code (during the [validate API request](https://github.com/hashgraph/hedera-json-rpc-relay/blob/7796aca3d8028e9732c58fb6855bef4520c4b3cc/packages/relay/src/lib/eth.ts#L643) and during the [precheck transaction](https://github.com/hashgraph/hedera-json-rpc-relay/blob/7796aca3d8028e9732c58fb6855bef4520c4b3cc/packages/relay/src/lib/precheck.ts#L64)).

I removed these checks and was able to send a [correct 0-value transaction](https://hashscan.io/testnet/tx/0x29d9264df7244583e69bdb41822887df2511b6ce8b10463280bc8260abb3c778) to the network.

### Solution

- Let the JSON-RPC relay operator decide whether to accept 0-value transactions.
- Set the default for this parameter to `true`: 0-value transactions are accepted.

### Alternatives

_No response_

### PR DESCRIPTION
**Pull request by simzzz**
**Description**:
This PR fixes the case where transactions with a value of 0 would not pass. This is needed because they would pass as valid transactions on the Ethereum network as 0 is a valid value there.

**Related issue(s)**:

Fixes #3105 

**Notes for reviewer**:

**Checklist**

- [x] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

### CODE REVIEW

File: packages/relay/src/lib/precheck.ts [hunk 1]
```diff
@@ -56,16 +57,6 @@ export class Precheck {
...
 
-  /**
-   * Checks if the value of the transaction is valid.
-   * @param {Transaction} tx - The transaction.
-   */
-  value(tx: Transaction): void {
-    if (tx.data === EthImpl.emptyHex && tx.value < constants.TINYBAR_TO_WEIBAR_COEF) {
-      throw predefined.VALUE_TOO_LOW;
-    }
-  }
```
Comment (vyanev1) [inline packages/relay/src/lib/precheck.ts:67]: I think we still want to check that the `tx.value` is not negative, instead of completely removing the pre-check

**Review by vyanev1 — CHANGES_REQUESTED** [review]
LG, one concern:

File: packages/relay/src/lib/precheck.ts (hunk 1 above)
Comment (victor-yanev) [inline packages/relay/src/lib/precheck.ts:67]: I think we still want to confirm that the value is not negative instead of completely removing the pre-check

**Review by victor-yanev — CHANGES_REQUESTED** [review]
LG, just once concern:

File: packages/relay/src/lib/precheck.ts (hunk 1 above)
Comment (simzzz) [reply packages/relay/src/lib/precheck.ts:67]: good point, the value shouldn't be below under 1 tinybar but 0 should be a valid value. I will push a new commit along with new tests for this

**Review by nadezhdapopovaa — DISMISSED** [review]

File: packages/relay/src/lib/precheck.ts [hunk 2]
```diff
@@ -61,7 +62,10 @@ export class Precheck {
    * @param {Transaction} tx - The transaction.
    */
   value(tx: Transaction): void {
-    if (tx.data === EthImpl.emptyHex && tx.value < constants.TINYBAR_TO_WEIBAR_COEF) {
+    if (
+      tx.data === EthImpl.emptyHex &&
+      ((tx.value > 0 && tx.value < constants.TINYBAR_TO_WEIBAR_COEF) || tx.value < 0)
+    ) {
```
Comment (victor-yanev) [inline packages/relay/src/lib/precheck.ts:68]: Don't we also want to perform this pre-check on non-zero data transaction? 

What if the solidity method is marked as payable and we pass a negative value or a value between 0 and `TINYBAR_TO_WEIBAR_COEF`? Don't we want to confirm that the passed value is correct also in this case?

**Review by victor-yanev — CHANGES_REQUESTED** [review]

**Review by victor-yanev — APPROVED** [review]

**Review by nadezhdapopovaa — DISMISSED** [review]

File: packages/relay/src/lib/errors/JsonRpcError.ts [hunk 3]
```diff
@@ -162,7 +162,7 @@ export const predefined = {
   }),
   VALUE_TOO_LOW: new JsonRpcError({
     code: -32602,
-    message: 'Value below 10_000_000_000 wei which is 1 tinybar',
+    message: "Value can't be negative or between 1 wei and 10_000_000_000 wei which is 1 tinybar",
```
Comment (Nana-EC) [inline packages/relay/src/lib/errors/JsonRpcError.ts:165]: nit: Maybe this is more clear
```suggestion
    message: "Value can't be non-zero and less than 10_000_000_000 wei which is 1 tinybar",
```

**Review by Nana-EC — DISMISSED** [review]
LG, one nit

**Review by quiet-node — APPROVED** [review]
Great work! LGTM

**Review by nadezhdapopovaa — APPROVED** [review]
