### PR TITLE
fix: Added HBar rate limiter to createFile

### LINKED ISSUE #2631: Add rateLimiter to the create file in the sdkClient
### Description

A large percentage of the relay's HBar is spent on file appends.  The HBar rate limiter needs to be added to the `createFile` method in the `sdkClient`.

### Steps to reproduce

Look at the relay's dashboard, under "Usage - HBar Accounts and Burn Rates".  Notice the `fileAppendTransaction` is over 80% of the "HBar Spent by Type".

### Additional context

_No response_

### Hedera network

mainnet

### Version

v0.50.0

### Operating system

Linux

### PR DESCRIPTION
**Pull request by ebadiere**
Added HBar rate limiting to sdkClient.createFile.

**Related issue(s)**:

Fixes #2631

### CODE REVIEW

File: packages/relay/src/lib/clients/sdkClient.ts [hunk 1]
```diff
@@ -643,60 +644,142 @@ export class SDKClient {
...
 
       this.captureMetrics(
         SDKClient.transactionMode,
-        fileAppendTx.constructor.name,
+        fileCreateTx.constructor.name,
         Status.Success,
-        await this.calculateFileAppendTxTotalTinybarsCost(fileAppendTx),
-        0,
+        createFileRecord.transactionFee.toTinybars().toNumber(),
+        createFileRecord?.contractFunctionResult?.gasUsed,
```
Comment (Nana-EC) [inline packages/relay/src/lib/clients/sdkClient.ts:679]: make this 0, no gas is utilized on FileCreate/FileAppend

File: packages/relay/src/lib/clients/sdkClient.ts [hunk 2]
```diff
@@ -643,60 +644,142 @@ export class SDKClient {
...
+            SDKClient.transactionMode,
+            fileCreateTx.constructor.name,
+            sdkClientError.status,
+            transactionFee.toTinybars().toNumber(),
+            transactionCreateRecord?.contractFunctionResult?.gasUsed,
+            callerName,
+            interactingEntity,
+          );
+
+          const transactionAppendRecord = await new TransactionRecordQuery()
```
Comment (Nana-EC) [inline packages/relay/src/lib/clients/sdkClient.ts:744]: Check for null `fileAppendTx`

File: packages/relay/src/lib/clients/sdkClient.ts [hunk 3]
```diff
@@ -643,60 +644,142 @@ export class SDKClient {
...
+            SDKClient.transactionMode,
+            fileCreateTx.constructor.name,
+            sdkClientError.status,
+            transactionFee.toTinybars().toNumber(),
+            transactionCreateRecord?.contractFunctionResult?.gasUsed,
+            callerName,
+            interactingEntity,
+          );
+
+          this.logger.info(
```
Comment (Nana-EC) [inline packages/relay/src/lib/clients/sdkClient.ts:762]: Add logic to log for both FileCreate and `FileAppend` separately if applicable

**Review by Nana-EC — CHANGES_REQUESTED** [review]

File: packages/relay/src/lib/clients/sdkClient.ts (hunk 1 above)
Comment (ebadiere) [reply packages/relay/src/lib/clients/sdkClient.ts:679]: Agreed, but I'll do this in a separate issue as it is unrelated to the HBar spend and has existed there for a while.

File: packages/relay/src/lib/clients/sdkClient.ts (hunk 2 above)
Comment (ebadiere) [reply packages/relay/src/lib/clients/sdkClient.ts:744]: Done.

File: packages/relay/src/lib/clients/sdkClient.ts (hunk 3 above)
Comment (ebadiere) [reply packages/relay/src/lib/clients/sdkClient.ts:762]: Done.

**Review by quiet-node — APPROVED** [review]
LGTM

File: packages/relay/src/lib/clients/sdkClient.ts [hunk 4]
```diff
@@ -643,60 +644,148 @@ export class SDKClient {
...
+            SDKClient.transactionMode,
+            fileCreateTx.constructor.name,
+            sdkClientError.status,
+            transactionFee.toTinybars().toNumber(),
+            transactionCreateRecord?.contractFunctionResult?.gasUsed,
+            callerName,
+            interactingEntity,
+          );
+
+          if (fileAppendTx === null || fileAppendTx === undefined) {
```
Comment (Nana-EC) [inline packages/relay/src/lib/clients/sdkClient.ts:744]: Logic path is a little off here and will result in a missing log for the fileAppend details.
If you got here there's certainly a create transaction so you can log that.
The should be a simple if that based on the presence of the `fileAppendTx` does all the associated logic.

File: packages/relay/src/lib/clients/sdkClient.ts [hunk 5]
```diff
@@ -643,60 +644,148 @@ export class SDKClient {
...
+              fileCreateTx.constructor.name,
+              sdkClientError.status,
+              transactionFee.toTinybars().toNumber(),
+              transactionCreateRecord?.contractFunctionResult?.gasUsed,
+              callerName,
+              interactingEntity,
+            );
+
+            this.logger.info(
+              `${requestIdPrefix} ${fileCreateTx.transactionId} ${callerName} ${fileCreateTx.constructor.name} status: ${sdkClientError.status} (${sdkClientError.status._code}), cost: ${transactionFee}`,
```
Comment (Nana-EC) [inline packages/relay/src/lib/clients/sdkClient.ts:768]: Based on above comment this would be updated as follows inside a if (fileAppendTx( {...}
```suggestion
              `${requestIdPrefix} ${fileAppendTx.transactionId} ${callerName} ${fileCreateTx.constructor.name} status: ${sdkClientError.status} (${sdkClientError.status._code}), cost: ${transactionFee}`,
```

File: packages/relay/tests/lib/sdkClient.spec.ts [hunk 6]
```diff
@@ -271,4 +272,1815 @@ describe('SdkClient', async function () {
       }
     });
   });
+
+  describe('Rate Limiter', async () => {
+    const transactionBuffer = new Uint8Array([
```
Comment (Nana-EC) [inline packages/relay/tests/lib/sdkClient.spec.ts:277]: nit: better approach would have been to just read in a file with some details. Actually contract byte code from one of the test  contracts would have been appropriate here

**Review by Nana-EC — APPROVED** [review]
Unblocking but please correct the logging item.
The rest can be done in follow up

File: packages/relay/src/lib/clients/sdkClient.ts [hunk 7]
```diff
@@ -643,60 +644,146 @@ export class SDKClient {
...
+            SDKClient.transactionMode,
+            fileCreateTx.constructor.name,
+            sdkClientError.status,
+            transactionFee.toTinybars().toNumber(),
+            transactionCreateRecord?.contractFunctionResult?.gasUsed,
+            callerName,
+            interactingEntity,
+          );
+
+          if (fileAppendTx === null || fileAppendTx === undefined) {
```
Comment (Nana-EC) [inline packages/relay/src/lib/clients/sdkClient.ts:744]: Below is what i'm suggesting.
Otherwise when you have an `fileAppendTx` you won't log the `fileCreateTx` details
```ts
            this.logger.info(
              `${requestIdPrefix} ${fileCreateTx.transactionId} ${callerName} ${fileCreateTx.constructor.name} status: ${sdkClientError.status} (${sdkClientError.status._code}), cost: ${transactionFee}`,
            );

        if (fileAppendTx) {
            const transactionAppendRecord = await new TransactionRecordQuery()
              .setTransactionId(fileAppendTx.transactionId!)
              .setNodeAccountIds(fileAppendTx.nodeAccountIds!)
              .setValidateReceiptStatus(false)
              .execute(this.clientMain);
            transactionFee = transactionAppendRecord.transactionFee;
            this.hbarLimiter.addExpense(transactionFee.toTinybars().toNumber(), currentDateNow);

            this.captureMetrics(
              SDKClient.transactionMode,
              fileCreateTx.constructor.name,
              sdkClientError.status,
              transactionFee.toTinybars().toNumber(),
              transactionCreateRecord?.contractFunctionResult?.gasUsed,
              callerName,
              interactingEntity,
            );

            this.logger.info(
              `${requestIdPrefix} ${fileAppendTx.transactionId} ${callerName} ${fileAppendTx.constructor.name} status: ${sdkClientError.status} (${sdkClientError.status._code}), cost: ${transactionFee}`,
            );
          }
```

**Review by Nana-EC — COMMENTED** [review]
Suggestion provided

File: packages/relay/src/lib/clients/sdkClient.ts [hunk 8]
```diff
@@ -643,60 +644,146 @@ export class SDKClient {
...
+      return fileId;
+    } catch (error: any) {
+      const sdkClientError = new SDKClientError(error, error.message);
+      let transactionFee: number | Hbar = 0;
+
+      // if valid network error utilize transaction id
+      if (sdkClientError.isValidNetworkError()) {
+        try {
+          const transactionCreateRecord = await new TransactionRecordQuery()
+            .setTransactionId(fileCreateTx.transactionId!)
```
Comment (quiet-node) [inline packages/relay/src/lib/clients/sdkClient.ts:727]: This `fileCreateTx` is always null as initialized with no value at [line 654](https://github.com/hashgraph/hedera-json-rpc-relay/pull/2634/files#diff-4b0bcc39d9efb3e923f041c7459f1cc42d34597d4200839df6764c2a345a1c1bR654)

File: packages/relay/src/lib/clients/sdkClient.ts (hunk 7 above)
Comment (quiet-node) [inline packages/relay/src/lib/clients/sdkClient.ts:744]: This `fileAppendTx` is always null as initialized with no value at [line 654](https://github.com/hashgraph/hedera-json-rpc-relay/pull/2634/files#diff-4b0bcc39d9efb3e923f041c7459f1cc42d34597d4200839df6764c2a345a1c1bR654)

Comment (ebadiere) [reply packages/relay/src/lib/clients/sdkClient.ts]: Done.

File: packages/relay/src/lib/clients/sdkClient.ts (hunk 8 above)
Comment (ebadiere) [reply packages/relay/src/lib/clients/sdkClient.ts:727]: Applied suggested fix which resolves this

File: packages/relay/src/lib/clients/sdkClient.ts (hunk 7 above)
Comment (ebadiere) [reply packages/relay/src/lib/clients/sdkClient.ts]: Applied suggested fix which resolves this

**Review by quiet-node — APPROVED** [review]

File: packages/relay/tests/lib/sdkClient.spec.ts (hunk 6 above)
Comment (Nana-EC) [reply packages/relay/tests/lib/sdkClient.spec.ts:277]: Resolving but @ebadiere we should resolve this in follow up
