### PR TITLE
DApp Test stuck running bootstrap action step

### LINKED ISSUE #499: DApp Test stuck running bootstrap action step
### Description

DApp tests seem to be running for lengthy periods and not finishing after starting the bootstrap step
See attempts here https://github.com/hashgraph/hedera-json-rpc-relay/actions/runs/3001062948

### Steps to reproduce

Publish PR running DApp tests

### Additional context

_No response_

### Hedera network

other

### Version

v0.8.0-SNAPSHOT

### Operating system

_No response_

### PR DESCRIPTION
**Pull request by natanasow**
Signed-off-by: nikolay <n.atanasow94@gmail.com>

**Description**:
DApp tests were stalling due to
- bump hashgraph/hedera-local to 1.2.0
- Update `npx hedera-local` commands to use `npx hedera`
- Bump server acceptance test `prerequisite.ts` to use services `0.30.0-alpha.0` and mirror node `0.64.0-beta2`
- Update restart command from `npx hedera-local` to `npx hedera restart -h localhost -d`

**Related issue(s)**:

Fixes #499

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

### CODE REVIEW

File: dapp-example/tests/support/bootstrap.js [hunk 1]
```diff
@@ -29,6 +29,7 @@ if (supportedEnvs.includes(network.toLowerCase())) {
 
 client.setOperator(process.env.OPERATOR_ID_MAIN, process.env.OPERATOR_KEY_MAIN);
 console.log(`SDK setup for ${JSON.stringify(network)} for account: ${process.env.OPERATOR_ID_MAIN}`);
+console.log('Debugging');
```
Comment (Nana-EC) [inline dapp-example/tests/support/bootstrap.js:32]: Lol, how does this fix it?

Comment (Nana-EC) [reply dapp-example/tests/support/bootstrap.js:32]: Also we should fix main first since more PRs are going there and can chrery pick the final fix over once confirmed.

Comment (natanasow) [reply dapp-example/tests/support/bootstrap.js:32]: It's not fixing it, I'm just testing... and the ci was completed successfully :confused:

Comment (natanasow) [reply dapp-example/tests/support/bootstrap.js:32]: Marked the PR as a draft till debugging it.

**Review by Nana-EC — APPROVED** [review]
LG

**Comment by Nana-EC** [comment]
@natanasow please update PR comments also :) 
Thanks for the fix

File: packages/server/tests/helpers/prerequisite.ts [hunk 2]
```diff
@@ -11,14 +11,14 @@ const RELAY_URL = process.env.E2E_RELAY_HOST || LOCAL_RELAY_URL;
 
 (function () {
   if (USE_LOCAL_NODE) {
-    process.env['NETWORK_NODE_IMAGE_TAG'] = '0.29.0-alpha.1';
-    process.env['HAVEGED_IMAGE_TAG'] = '0.29.0-alpha.1';
-    process.env['MIRROR_IMAGE_TAG'] = '0.62.0-rc1';
+    process.env['NETWORK_NODE_IMAGE_TAG'] = '0.30.0-alpha.0';
+    process.env['HAVEGED_IMAGE_TAG'] = '0.30.0-alpha.0';
+    process.env['MIRROR_IMAGE_TAG'] = '0.64.0-beta2';
```
[the remark this answers is not in the document]
Comment (Nana-EC) [reply packages/server/tests/helpers/prerequisite.ts:16]: Will update in my PR
