### PR TITLE
Handle empty state_changes array in contract details

### LINKED ISSUE #732: Failed to send/recv `storage` err=GetStorage() when testing with Foundry
### Description

I have successfully set up Foundry to work with Hedera by configuring it to work with npm modules. We can run unit test, and complete fuzz testing. Github repo [here](https://github.com/a-ridley/hedera-smart-contract-testing-with-foundry).

The issue lies when attempting to use Foundry's fork testing to test against a smart contract that is deployed on testnet. In my test set up, I provided my smart contract's evm address (which I grabbed from hashscan).

Below is a snippet of my test set up.
```
function setUp() public {
        counter = Counter(0x0000000000000000000000000000000002Eba2A0);
        //counter.setNumber(0);
    }
```

The expected output is for my tests to run successfully. However, the result of running my tests gives the following error:

```
2022-12-01T18:28:36.945764Z ERROR sharedbackend: Failed to send/recv `storage` err=GetStorage(0x0000000000000000000000000000000002eba2a0, 0, 
(code: -32603, message: [Request ID: 6153887f-a84f-42e9-93c7-8fcb32047a21] Error invoking RPC: , data: None)) address=0x0000000000000000000000000000000002eba2a0 index=0

Running 1 test for test/foundry/Counter.t.sol:CounterTest
[FAIL. Reason: EvmError: FatalExternalError] testIncrement() (gas: 9223372036854754743)
Test result: FAILED. 0 passed; 1 failed; finished in 38.01s

Failing tests:
Encountered 1 failing test in test/foundry/Counter.t.sol:CounterTest
[FAIL. Reason: EvmError: FatalExternalError] testIncrement() (gas: 9223372036854754743)
```

### Steps to reproduce

1. Unzip the project below and open it in vscode
[simulate-swap-hedera.zip](https://github.com/hashgraph/hedera-json-rpc-relay/files/10137040/simulate-swap-hedera.zip)
2. edit the .env file
3. Open a terminal in the project's dir
4. run `HEDERA_RPC_URL=https://testnet.hashio.io/api `
5. run `forge test --fork-url $HEDERA_RPC_URL -vv --fork-block-number <block number>`

### Additional context

**note: block number needs to be at least 15 minutes in the past or you'll get the error below.**
`(code: -32007, message: [Request ID: 3804b205-6ef8-471d-92a2-e640d9131558] Historical balance data is available only after 15 minutes., data: None)) address=0x0000000000000000000000000000000002eba2a0`

### Hedera network

testnet

### Version

v2.18.5

### Operating system

macOS

### PR DESCRIPTION
**Pull request by lukelee-sl**
Signed-off-by: lukelee-sl <luke.lee@swirldslabs.com>

Handle the case when the state_changes field returned as an empty array. 

Fixes #732 

- [ ] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

### CODE REVIEW

File: packages/relay/src/lib/eth.ts [hunk 1]
```diff
@@ -498,7 +499,7 @@ export class EthImpl implements Eth {
       // retrieve the contract result details
       await this.mirrorNodeClient.getContractResultsDetails(address, contractResult.results[0].timestamp)
         .then(contractResultDetails => {
-          if (contractResultDetails?.state_changes != null) {
+          if (contractResultDetails?.state_changes != null && Array.isArray(contractResultDetails?.state_changes) && contractResultDetails?.state_changes.length > 0) {
```
Comment (david-bakin-sl) [inline packages/relay/src/lib/eth.ts:502]: this one-liner should be a utility function somewhere, isn't it somewhere else already?  (typescript doesn't have it as a built-in?)

Comment (Nana-EC) [inline packages/relay/src/lib/eth.ts:502]: `Array.isArray(null)` and `Array.isArray(undefined)` returns false so we can drop the initial null check
```suggestion
          if (Array.isArray(contractResultDetails?.state_changes) && contractResultDetails?.state_changes.length > 0) {
```

File: packages/relay/tests/lib/eth.spec.ts [hunk 2]
```diff
@@ -2219,6 +2231,38 @@ describe('Eth calls using MirrorNode', async function () {
...
+      defaultDetailedContractResultsNullStateChange
+      mock.onGet(`blocks/${blockNumber}`).reply(200, defaultBlock);
+      mock.onGet(`contracts/${contractAddress1}/results?timestamp=lte:${defaultBlock.timestamp.to}&limit=1&order=desc`).reply(200, defaultContractResults);
+      mock.onGet(`contracts/${contractAddress1}/results/${contractTimestamp1}`).reply(200, defaultDetailedContractResultsNullStateChange);
+      let hasError = false;
+      try {
+        await ethImpl.getStorageAt(contractAddress1, defaultDetailedContractResults.state_changes[0].slot, EthImpl.numberTo0x(blockNumber));
+      } catch (e: any) {
+        hasError = true;
+        expect(e.code).to.equal(-32001);
```
Comment (david-bakin-sl) [inline packages/relay/tests/lib/eth.spec.ts:2244]: Is this magic number something I should just know were I working with typescript?

**Review by Nana-EC — COMMENTED** [review]
LG, offered a simplification

File: packages/relay/tests/lib/eth.spec.ts (hunk 2 above)
Comment (Nana-EC) [reply packages/relay/tests/lib/eth.spec.ts:2244]: It's the [RESOURCE_NOT_FOUND error code](https://github.com/hashgraph/hedera-json-rpc-relay/blob/main/packages/relay/src/lib/errors/JsonRpcError.ts#L118)

Comment (Nana-EC) [reply packages/relay/tests/lib/eth.spec.ts:2244]: Might be good to use `predefined.RESOURCE_NOT_FOUND.code` in the check instead

File: packages/relay/src/lib/eth.ts (hunk 1 above)
Comment (lukelee-sl) [reply packages/relay/src/lib/eth.ts:502]: no built-in function that I am aware of

File: packages/relay/tests/lib/eth.spec.ts (hunk 2 above)
Comment (lukelee-sl) [reply packages/relay/tests/lib/eth.spec.ts]: done

File: packages/relay/src/lib/eth.ts (hunk 1 above)
Comment (david-bakin-sl) [reply packages/relay/src/lib/eth.ts]: (stupid mis-hit button ate my comment) the concept being expressed here "array must not be empty" is needlessly complicated when written out due to javascript/java/c# stupidity of allowing arrays to be "null" as a distinct thing to test syntactically than array being/not being empty.  So here, even with this simplification, it takes an entire line to express and a pattern match in your brain to figure out the idiom - again complicated because it is done w.r.t. to a named field of an object which itself takes 40 characters to express and you have to say it twice.  My suggestion would be to extract it into a named method - even though the method itself might be a one-liner - so that every _use_ is simplified and the name alone is sufficient to tell you what's going on - you don't have to recognize the pattern.  (Except of course the language might not actually allow you to easily express the method _call_.)

Comment (lukelee-sl) [reply packages/relay/src/lib/eth.ts]: I understand the sentiment.  With issues like this, I like to ask myself "does doing this lessen the likelihood of a mistake?".  If so then I create the helper static method.  I think one needs to be careful or you could spend so much time creating helper/macro methods, the code becomes difficult to follow (I've followed too many #define references in header files in c++ to find at the end something trivial).  I'll take your council in this case.

**Comment by david-bakin-sl** [comment]
LGTM

**Review by Nana-EC — APPROVED** [review]
LGTM
