### PR TITLE
Handle Mirror Node network fee errors

### LINKED ISSUE #239: getFeeWeibars failing on mirror node network/fees 500
### Problem

The current version of the relay handles 404 for Mirror Node network/fees calls.
However, it doesn't have logic to support a 500 failure 

### Solution

Add logic to handle all error from mirror node call

### Alternatives

_No response_

### PR DESCRIPTION
**Pull request by Nana-EC**
Signed-off-by: Nana-EC <nana@swirldslabs.com>

**Description**:
Expand mirror node network fees fallback to encompass all errors
- Add warning log
- Expand test integration capabilities using `sinon`
- Add `eth.spec.ts` coverage for mirror node failures for gas endpoints

**Related issue(s)**:

Fixes #239 

**Notes for reviewer**:
Locally pointed against testnet backends to confirm fix

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

### CODE REVIEW

File: packages/relay/src/lib/eth.ts [hunk 1]
```diff
@@ -147,7 +147,13 @@ export class EthImpl implements Eth {
   }
 
   private async getFeeWeibars() {
-    let networkFees = await this.mirrorNodeClient.getNetworkFees();
+    let networkFees;
+
+    try {
+      networkFees = await this.mirrorNodeClient.getNetworkFees();
+    } catch (e: any) {
+      this.logger.debug(`Failed to retrieve Network fees from Mirror Node`);
```
Comment (steven-sheehy) [inline packages/relay/src/lib/eth.ts:155]: Should log at the underlying error message

File: packages/relay/src/lib/eth.ts [hunk 2]
```diff
@@ -147,7 +147,13 @@ export class EthImpl implements Eth {
...
+    }
 
     if (_.isNil(networkFees)) {
       this.logger.debug(`Mirror Node returned no fees. Fallback to network`);
```
Comment (steven-sheehy) [inline packages/relay/src/lib/eth.ts:159]: This will log two statements for one error scenario, which is not ideal.

File: packages/relay/src/lib/eth.ts (hunk 1 above)
Comment (steven-sheehy) [inline packages/relay/src/lib/eth.ts:155]: Should be warn level if an upstream has an error.

**Review by steven-sheehy — CHANGES_REQUESTED** [review]

File: packages/relay/src/lib/eth.ts (hunk 1 above)
Comment (Nana-EC) [reply packages/relay/src/lib/eth.ts]: Captured underlying error

File: packages/relay/src/lib/eth.ts (hunk 2 above)
Comment (Nana-EC) [reply packages/relay/src/lib/eth.ts]: Moved up so only 1 of the 2 logs show up

File: packages/relay/src/lib/eth.ts (hunk 1 above)
Comment (Nana-EC) [reply packages/relay/src/lib/eth.ts]: Updated to warn

File: packages/relay/src/lib/eth.ts [hunk 3]
```diff
@@ -147,10 +147,16 @@ export class EthImpl implements Eth {
   }
 
   private async getFeeWeibars() {
-    let networkFees = await this.mirrorNodeClient.getNetworkFees();
+    let networkFees;
 
-    if (_.isNil(networkFees)) {
+    try {
+      networkFees = await this.mirrorNodeClient.getNetworkFees();
       this.logger.debug(`Mirror Node returned no fees. Fallback to network`);
```
Comment (steven-sheehy) [inline packages/relay/src/lib/eth.ts:154]: This log would also occur if the mirror node did return fees successfully

Comment (Nana-EC) [reply packages/relay/src/lib/eth.ts]: Missed that. Updated

**Review by steven-sheehy — APPROVED** [review]
