### PR TITLE
return 0x instead of 0x0 for non existing contract addresses given to…

### LINKED ISSUE #394: eth_getCode returning 0x0 instead of 0x for non-contract addresses
### Description

When making a request using the eth_getCode method for a non-contract address, the result value returned is 0x0. Other relays (such as Ethereum or BSC relays) return 0x. This can cause issues if applications or libraries are expecting 0x but not 0x0. 

It might be worth modifying the result value to return 0x to cover applications or libraries that do not expect 0x0, especially if this is standard for relays on other chains.

### Steps to reproduce

1. Make a request to the JSON RPC relay with the eth_getCode method for a non-contract address

`curl -X POST -H 'Content-Type: application/json' -d '{"jsonrpc":"2.0","id":"2","method":"eth_getCode","params":["0x0000000000000000000000000000000000000000", "latest"]}' https://testnet.hashio.io/api`

Response received:
`{"result":"0x0","jsonrpc":"2.0","id":"2"}`

Response expected:
`{"result":"0x","jsonrpc":"2.0","id":"2"}`

### Additional context

_No response_

### Hedera network

mainnet, testnet, previewnet, other

### Version

v0.3.0

### Operating system

macOS

### PR DESCRIPTION
**Pull request by lukelee-sl**
… eth_getCode

Signed-off-by: lukelee-sl <luke.lee@swirldslabs.com>

**Description**:
In order to be more consistent with other relays, return 0x instead of 0x0 when sending a non existing contract address to the eth_getCode call.

Modified code in the error condition when we are given an invalid contract.

**Related issue(s)**:

Fixes #394 

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

### CODE REVIEW

File: packages/relay/src/lib/eth.ts [hunk 1]
```diff
@@ -494,8 +494,8 @@ export class EthImpl implements Eth {
         // handle INVALID_CONTRACT_ID
         if (e.isInvalidContractId()) {
           this.logger.debug('Unable to find code for contract %s in block "%s", returning 0x0, err code: %s', address, blockNumber, e.statusCode);
-          cache.set(cachedLabel, '0x0', constants.CACHE_TTL.ONE_HOUR);
-          return '0x0';
+          cache.set(cachedLabel, '0x', constants.CACHE_TTL.ONE_HOUR);
+          return '0x';
```
Comment (Nana-EC) [inline packages/relay/src/lib/eth.ts:498]: nit:
```suggestion
          return EthImpl.emptyHex;
```

Comment (Nana-EC) [reply packages/relay/src/lib/eth.ts:498]: Here and anywhere else it's easily available in your changes

**Review by Nana-EC — CHANGES_REQUESTED** [review]
LG, minor nit

**Review by Nana-EC — APPROVED** [review]
LGTM
